/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HttpMethod model module.
 * @module model/HttpMethod
 * @version v1
 */
class HttpMethod {
    /**
     * Constructs a new <code>HttpMethod</code>.
     * @alias module:model/HttpMethod
     */
    constructor() { 
        
        HttpMethod.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HttpMethod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HttpMethod} obj Optional instance to populate.
     * @return {module:model/HttpMethod} The populated <code>HttpMethod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HttpMethod();

            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} method
 */
HttpMethod.prototype['method'] = undefined;






export default HttpMethod;

