/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HttpContent from './HttpContent';
import HttpMethod from './HttpMethod';
import KeyValuePair2 from './KeyValuePair2';
import Version from './Version';

/**
 * The HttpRequestMessage model module.
 * @module model/HttpRequestMessage
 * @version v1
 */
class HttpRequestMessage {
    /**
     * Constructs a new <code>HttpRequestMessage</code>.
     * @alias module:model/HttpRequestMessage
     */
    constructor() { 
        
        HttpRequestMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HttpRequestMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HttpRequestMessage} obj Optional instance to populate.
     * @return {module:model/HttpRequestMessage} The populated <code>HttpRequestMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HttpRequestMessage();

            if (data.hasOwnProperty('version')) {
                obj['version'] = Version.constructFromObject(data['version']);
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = HttpContent.constructFromObject(data['content']);
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = HttpMethod.constructFromObject(data['method']);
            }
            if (data.hasOwnProperty('requestUri')) {
                obj['requestUri'] = ApiClient.convertToType(data['requestUri'], 'String');
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], [KeyValuePair2]);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Version} version
 */
HttpRequestMessage.prototype['version'] = undefined;

/**
 * @member {module:model/HttpContent} content
 */
HttpRequestMessage.prototype['content'] = undefined;

/**
 * @member {module:model/HttpMethod} method
 */
HttpRequestMessage.prototype['method'] = undefined;

/**
 * @member {String} requestUri
 */
HttpRequestMessage.prototype['requestUri'] = undefined;

/**
 * @member {Array.<module:model/KeyValuePair2>} headers
 */
HttpRequestMessage.prototype['headers'] = undefined;

/**
 * @member {Object.<String, Object>} properties
 */
HttpRequestMessage.prototype['properties'] = undefined;






export default HttpRequestMessage;

