/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsDevAccountMember model module.
 * @module model/MozuAppDevContractsDevAccountMember
 * @version v1
 */
class MozuAppDevContractsDevAccountMember {
    /**
     * Constructs a new <code>MozuAppDevContractsDevAccountMember</code>.
     * @alias module:model/MozuAppDevContractsDevAccountMember
     */
    constructor() { 
        
        MozuAppDevContractsDevAccountMember.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsDevAccountMember</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsDevAccountMember} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsDevAccountMember} The populated <code>MozuAppDevContractsDevAccountMember</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsDevAccountMember();

            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('dateLastSent')) {
                obj['dateLastSent'] = ApiClient.convertToType(data['dateLastSent'], 'Date');
            }
            if (data.hasOwnProperty('invitationState')) {
                obj['invitationState'] = ApiClient.convertToType(data['invitationState'], 'String');
            }
            if (data.hasOwnProperty('invitationId')) {
                obj['invitationId'] = ApiClient.convertToType(data['invitationId'], 'String');
            }
            if (data.hasOwnProperty('roleId')) {
                obj['roleId'] = ApiClient.convertToType(data['roleId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} emailAddress
 */
MozuAppDevContractsDevAccountMember.prototype['emailAddress'] = undefined;

/**
 * @member {String} firstName
 */
MozuAppDevContractsDevAccountMember.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
MozuAppDevContractsDevAccountMember.prototype['lastName'] = undefined;

/**
 * @member {String} userId
 */
MozuAppDevContractsDevAccountMember.prototype['userId'] = undefined;

/**
 * @member {Date} dateLastSent
 */
MozuAppDevContractsDevAccountMember.prototype['dateLastSent'] = undefined;

/**
 * @member {String} invitationState
 */
MozuAppDevContractsDevAccountMember.prototype['invitationState'] = undefined;

/**
 * @member {String} invitationId
 */
MozuAppDevContractsDevAccountMember.prototype['invitationId'] = undefined;

/**
 * @member {Number} roleId
 */
MozuAppDevContractsDevAccountMember.prototype['roleId'] = undefined;






export default MozuAppDevContractsDevAccountMember;

