/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuCoreApiContractsUserRole from './MozuCoreApiContractsUserRole';
import MozuCoreApiContractsUserSystemData from './MozuCoreApiContractsUserSystemData';

/**
 * The MozuCoreApiContractsUser model module.
 * @module model/MozuCoreApiContractsUser
 * @version v1
 */
class MozuCoreApiContractsUser {
    /**
     * Constructs a new <code>MozuCoreApiContractsUser</code>.
     * @alias module:model/MozuCoreApiContractsUser
     */
    constructor() { 
        
        MozuCoreApiContractsUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreApiContractsUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreApiContractsUser} obj Optional instance to populate.
     * @return {module:model/MozuCoreApiContractsUser} The populated <code>MozuCoreApiContractsUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreApiContractsUser();

            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('localeCode')) {
                obj['localeCode'] = ApiClient.convertToType(data['localeCode'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('optInToEmail')) {
                obj['optInToEmail'] = ApiClient.convertToType(data['optInToEmail'], 'Boolean');
            }
            if (data.hasOwnProperty('optInToTextMessage')) {
                obj['optInToTextMessage'] = ApiClient.convertToType(data['optInToTextMessage'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('systemData')) {
                obj['systemData'] = MozuCoreApiContractsUserSystemData.constructFromObject(data['systemData']);
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], [MozuCoreApiContractsUserRole]);
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} emailAddress
 */
MozuCoreApiContractsUser.prototype['emailAddress'] = undefined;

/**
 * @member {String} userName
 */
MozuCoreApiContractsUser.prototype['userName'] = undefined;

/**
 * @member {String} phoneNumber
 */
MozuCoreApiContractsUser.prototype['phoneNumber'] = undefined;

/**
 * @member {String} externalId
 */
MozuCoreApiContractsUser.prototype['externalId'] = undefined;

/**
 * @member {String} localeCode
 */
MozuCoreApiContractsUser.prototype['localeCode'] = undefined;

/**
 * @member {String} firstName
 */
MozuCoreApiContractsUser.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
MozuCoreApiContractsUser.prototype['lastName'] = undefined;

/**
 * @member {String} password
 */
MozuCoreApiContractsUser.prototype['password'] = undefined;

/**
 * @member {Boolean} optInToEmail
 */
MozuCoreApiContractsUser.prototype['optInToEmail'] = undefined;

/**
 * @member {Boolean} optInToTextMessage
 */
MozuCoreApiContractsUser.prototype['optInToTextMessage'] = undefined;

/**
 * @member {String} id
 */
MozuCoreApiContractsUser.prototype['id'] = undefined;

/**
 * @member {module:model/MozuCoreApiContractsUserSystemData} systemData
 */
MozuCoreApiContractsUser.prototype['systemData'] = undefined;

/**
 * @member {Array.<module:model/MozuCoreApiContractsUserRole>} roles
 */
MozuCoreApiContractsUser.prototype['roles'] = undefined;

/**
 * @member {Boolean} isActive
 */
MozuCoreApiContractsUser.prototype['isActive'] = undefined;






export default MozuCoreApiContractsUser;

