/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAdminUserContractsInvitationRole model module.
 * @module model/MozuAdminUserContractsInvitationRole
 * @version v1
 */
class MozuAdminUserContractsInvitationRole {
    /**
     * Constructs a new <code>MozuAdminUserContractsInvitationRole</code>.
     * @alias module:model/MozuAdminUserContractsInvitationRole
     */
    constructor() { 
        
        MozuAdminUserContractsInvitationRole.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAdminUserContractsInvitationRole</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAdminUserContractsInvitationRole} obj Optional instance to populate.
     * @return {module:model/MozuAdminUserContractsInvitationRole} The populated <code>MozuAdminUserContractsInvitationRole</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAdminUserContractsInvitationRole();

            if (data.hasOwnProperty('roleId')) {
                obj['roleId'] = ApiClient.convertToType(data['roleId'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} roleId
 */
MozuAdminUserContractsInvitationRole.prototype['roleId'] = undefined;

/**
 * @member {String} name
 */
MozuAdminUserContractsInvitationRole.prototype['name'] = undefined;






export default MozuAdminUserContractsInvitationRole;

