/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsAppVersion from './MozuAppDevContractsAppVersion';

/**
 * The MozuAppDevContractsTenantApplication model module.
 * @module model/MozuAppDevContractsTenantApplication
 * @version v1
 */
class MozuAppDevContractsTenantApplication {
    /**
     * Constructs a new <code>MozuAppDevContractsTenantApplication</code>.
     * @alias module:model/MozuAppDevContractsTenantApplication
     */
    constructor() { 
        
        MozuAppDevContractsTenantApplication.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsTenantApplication</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsTenantApplication} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsTenantApplication} The populated <code>MozuAppDevContractsTenantApplication</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsTenantApplication();

            if (data.hasOwnProperty('applicationId')) {
                obj['applicationId'] = ApiClient.convertToType(data['applicationId'], 'Number');
            }
            if (data.hasOwnProperty('applicationVersion')) {
                obj['applicationVersion'] = MozuAppDevContractsAppVersion.constructFromObject(data['applicationVersion']);
            }
            if (data.hasOwnProperty('applicationName')) {
                obj['applicationName'] = ApiClient.convertToType(data['applicationName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} applicationId
 */
MozuAppDevContractsTenantApplication.prototype['applicationId'] = undefined;

/**
 * @member {module:model/MozuAppDevContractsAppVersion} applicationVersion
 */
MozuAppDevContractsTenantApplication.prototype['applicationVersion'] = undefined;

/**
 * @member {String} applicationName
 */
MozuAppDevContractsTenantApplication.prototype['applicationName'] = undefined;






export default MozuAppDevContractsTenantApplication;

