/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsProvisionTenantRequest model module.
 * @module model/MozuAppDevContractsProvisionTenantRequest
 * @version v1
 */
class MozuAppDevContractsProvisionTenantRequest {
    /**
     * Constructs a new <code>MozuAppDevContractsProvisionTenantRequest</code>.
     * @alias module:model/MozuAppDevContractsProvisionTenantRequest
     */
    constructor() { 
        
        MozuAppDevContractsProvisionTenantRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsProvisionTenantRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsProvisionTenantRequest} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsProvisionTenantRequest} The populated <code>MozuAppDevContractsProvisionTenantRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsProvisionTenantRequest();

            if (data.hasOwnProperty('tenantName')) {
                obj['tenantName'] = ApiClient.convertToType(data['tenantName'], 'String');
            }
            if (data.hasOwnProperty('sourceTenantId')) {
                obj['sourceTenantId'] = ApiClient.convertToType(data['sourceTenantId'], 'Number');
            }
            if (data.hasOwnProperty('applicationIds')) {
                obj['applicationIds'] = ApiClient.convertToType(data['applicationIds'], ['Number']);
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'Number');
            }
            if (data.hasOwnProperty('localeCode')) {
                obj['localeCode'] = ApiClient.convertToType(data['localeCode'], 'String');
            }
            if (data.hasOwnProperty('currencyCode')) {
                obj['currencyCode'] = ApiClient.convertToType(data['currencyCode'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('enableBetaAdmin')) {
                obj['enableBetaAdmin'] = ApiClient.convertToType(data['enableBetaAdmin'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} tenantName
 */
MozuAppDevContractsProvisionTenantRequest.prototype['tenantName'] = undefined;

/**
 * @member {Number} sourceTenantId
 */
MozuAppDevContractsProvisionTenantRequest.prototype['sourceTenantId'] = undefined;

/**
 * @member {Array.<Number>} applicationIds
 */
MozuAppDevContractsProvisionTenantRequest.prototype['applicationIds'] = undefined;

/**
 * @member {Number} projectId
 */
MozuAppDevContractsProvisionTenantRequest.prototype['projectId'] = undefined;

/**
 * @member {String} localeCode
 */
MozuAppDevContractsProvisionTenantRequest.prototype['localeCode'] = undefined;

/**
 * @member {String} currencyCode
 */
MozuAppDevContractsProvisionTenantRequest.prototype['currencyCode'] = undefined;

/**
 * @member {String} countryCode
 */
MozuAppDevContractsProvisionTenantRequest.prototype['countryCode'] = undefined;

/**
 * @member {Boolean} enableBetaAdmin
 */
MozuAppDevContractsProvisionTenantRequest.prototype['enableBetaAdmin'] = undefined;






export default MozuAppDevContractsProvisionTenantRequest;

