/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsBehaviorItem from './MozuAppDevContractsBehaviorItem';

/**
 * The MozuAppDevContractsBehaviorCategoryBehavior model module.
 * @module model/MozuAppDevContractsBehaviorCategoryBehavior
 * @version v1
 */
class MozuAppDevContractsBehaviorCategoryBehavior {
    /**
     * Constructs a new <code>MozuAppDevContractsBehaviorCategoryBehavior</code>.
     * @alias module:model/MozuAppDevContractsBehaviorCategoryBehavior
     */
    constructor() { 
        
        MozuAppDevContractsBehaviorCategoryBehavior.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsBehaviorCategoryBehavior</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsBehaviorCategoryBehavior} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsBehaviorCategoryBehavior} The populated <code>MozuAppDevContractsBehaviorCategoryBehavior</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsBehaviorCategoryBehavior();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('behaviorItems')) {
                obj['behaviorItems'] = ApiClient.convertToType(data['behaviorItems'], [MozuAppDevContractsBehaviorItem]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsBehaviorCategoryBehavior.prototype['id'] = undefined;

/**
 * @member {String} name
 */
MozuAppDevContractsBehaviorCategoryBehavior.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsBehaviorItem>} behaviorItems
 */
MozuAppDevContractsBehaviorCategoryBehavior.prototype['behaviorItems'] = undefined;






export default MozuAppDevContractsBehaviorCategoryBehavior;

