/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAdminUserContractsInvitationRole from './MozuAdminUserContractsInvitationRole';
import MozuCoreApiContractsAuditInfo from './MozuCoreApiContractsAuditInfo';

/**
 * The MozuAdminUserContractsInvitation model module.
 * @module model/MozuAdminUserContractsInvitation
 * @version v1
 */
class MozuAdminUserContractsInvitation {
    /**
     * Constructs a new <code>MozuAdminUserContractsInvitation</code>.
     * @alias module:model/MozuAdminUserContractsInvitation
     */
    constructor() { 
        
        MozuAdminUserContractsInvitation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAdminUserContractsInvitation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAdminUserContractsInvitation} obj Optional instance to populate.
     * @return {module:model/MozuAdminUserContractsInvitation} The populated <code>MozuAdminUserContractsInvitation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAdminUserContractsInvitation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('userScopeType')) {
                obj['userScopeType'] = ApiClient.convertToType(data['userScopeType'], 'String');
            }
            if (data.hasOwnProperty('userScopeId')) {
                obj['userScopeId'] = ApiClient.convertToType(data['userScopeId'], 'Number');
            }
            if (data.hasOwnProperty('scopeName')) {
                obj['scopeName'] = ApiClient.convertToType(data['scopeName'], 'String');
            }
            if (data.hasOwnProperty('roleId')) {
                obj['roleId'] = ApiClient.convertToType(data['roleId'], 'Number');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('invitationRoles')) {
                obj['invitationRoles'] = ApiClient.convertToType(data['invitationRoles'], [MozuAdminUserContractsInvitationRole]);
            }
            if (data.hasOwnProperty('dateLastSent')) {
                obj['dateLastSent'] = ApiClient.convertToType(data['dateLastSent'], 'Date');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('auditInfo')) {
                obj['auditInfo'] = MozuCoreApiContractsAuditInfo.constructFromObject(data['auditInfo']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
MozuAdminUserContractsInvitation.prototype['id'] = undefined;

/**
 * @member {String} userScopeType
 */
MozuAdminUserContractsInvitation.prototype['userScopeType'] = undefined;

/**
 * @member {Number} userScopeId
 */
MozuAdminUserContractsInvitation.prototype['userScopeId'] = undefined;

/**
 * @member {String} scopeName
 */
MozuAdminUserContractsInvitation.prototype['scopeName'] = undefined;

/**
 * @member {Number} roleId
 */
MozuAdminUserContractsInvitation.prototype['roleId'] = undefined;

/**
 * @member {String} emailAddress
 */
MozuAdminUserContractsInvitation.prototype['emailAddress'] = undefined;

/**
 * @member {String} firstName
 */
MozuAdminUserContractsInvitation.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
MozuAdminUserContractsInvitation.prototype['lastName'] = undefined;

/**
 * @member {Array.<module:model/MozuAdminUserContractsInvitationRole>} invitationRoles
 */
MozuAdminUserContractsInvitation.prototype['invitationRoles'] = undefined;

/**
 * @member {Date} dateLastSent
 */
MozuAdminUserContractsInvitation.prototype['dateLastSent'] = undefined;

/**
 * @member {String} state
 */
MozuAdminUserContractsInvitation.prototype['state'] = undefined;

/**
 * @member {module:model/MozuCoreApiContractsAuditInfo} auditInfo
 */
MozuAdminUserContractsInvitation.prototype['auditInfo'] = undefined;






export default MozuAdminUserContractsInvitation;

