/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsEvent from './MozuAppDevContractsEvent';

/**
 * The MozuAppDevContractsApplicationSubscription model module.
 * @module model/MozuAppDevContractsApplicationSubscription
 * @version v1
 */
class MozuAppDevContractsApplicationSubscription {
    /**
     * Constructs a new <code>MozuAppDevContractsApplicationSubscription</code>.
     * @alias module:model/MozuAppDevContractsApplicationSubscription
     */
    constructor() { 
        
        MozuAppDevContractsApplicationSubscription.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsApplicationSubscription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsApplicationSubscription} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsApplicationSubscription} The populated <code>MozuAppDevContractsApplicationSubscription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsApplicationSubscription();

            if (data.hasOwnProperty('applicationSubscriptionId')) {
                obj['applicationSubscriptionId'] = ApiClient.convertToType(data['applicationSubscriptionId'], 'Number');
            }
            if (data.hasOwnProperty('applicationEndPoint')) {
                obj['applicationEndPoint'] = ApiClient.convertToType(data['applicationEndPoint'], 'String');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [MozuAppDevContractsEvent]);
            }
            if (data.hasOwnProperty('packageId')) {
                obj['packageId'] = ApiClient.convertToType(data['packageId'], 'Number');
            }
            if (data.hasOwnProperty('noCallback')) {
                obj['noCallback'] = ApiClient.convertToType(data['noCallback'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} applicationSubscriptionId
 */
MozuAppDevContractsApplicationSubscription.prototype['applicationSubscriptionId'] = undefined;

/**
 * @member {String} applicationEndPoint
 */
MozuAppDevContractsApplicationSubscription.prototype['applicationEndPoint'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsEvent>} events
 */
MozuAppDevContractsApplicationSubscription.prototype['events'] = undefined;

/**
 * @member {Number} packageId
 */
MozuAppDevContractsApplicationSubscription.prototype['packageId'] = undefined;

/**
 * @member {Boolean} noCallback
 */
MozuAppDevContractsApplicationSubscription.prototype['noCallback'] = undefined;






export default MozuAppDevContractsApplicationSubscription;

