/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuTenantContractsTenantAttribute model module.
 * @module model/MozuTenantContractsTenantAttribute
 * @version v1
 */
class MozuTenantContractsTenantAttribute {
    /**
     * Constructs a new <code>MozuTenantContractsTenantAttribute</code>.
     * @alias module:model/MozuTenantContractsTenantAttribute
     */
    constructor() { 
        
        MozuTenantContractsTenantAttribute.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuTenantContractsTenantAttribute</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuTenantContractsTenantAttribute} obj Optional instance to populate.
     * @return {module:model/MozuTenantContractsTenantAttribute} The populated <code>MozuTenantContractsTenantAttribute</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuTenantContractsTenantAttribute();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
            if (data.hasOwnProperty('createBy')) {
                obj['createBy'] = ApiClient.convertToType(data['createBy'], 'String');
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'Date');
            }
            if (data.hasOwnProperty('updateBy')) {
                obj['updateBy'] = ApiClient.convertToType(data['updateBy'], 'String');
            }
            if (data.hasOwnProperty('updateDate')) {
                obj['updateDate'] = ApiClient.convertToType(data['updateDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
MozuTenantContractsTenantAttribute.prototype['name'] = undefined;

/**
 * @member {Object} value
 */
MozuTenantContractsTenantAttribute.prototype['value'] = undefined;

/**
 * @member {String} createBy
 */
MozuTenantContractsTenantAttribute.prototype['createBy'] = undefined;

/**
 * @member {Date} createDate
 */
MozuTenantContractsTenantAttribute.prototype['createDate'] = undefined;

/**
 * @member {String} updateBy
 */
MozuTenantContractsTenantAttribute.prototype['updateBy'] = undefined;

/**
 * @member {Date} updateDate
 */
MozuTenantContractsTenantAttribute.prototype['updateDate'] = undefined;






export default MozuTenantContractsTenantAttribute;

