/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsProjectStatus model module.
 * @module model/MozuAppDevContractsProjectStatus
 * @version v1
 */
class MozuAppDevContractsProjectStatus {
    /**
     * Constructs a new <code>MozuAppDevContractsProjectStatus</code>.
     * @alias module:model/MozuAppDevContractsProjectStatus
     */
    constructor() { 
        
        MozuAppDevContractsProjectStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsProjectStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsProjectStatus} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsProjectStatus} The populated <code>MozuAppDevContractsProjectStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsProjectStatus();

            if (data.hasOwnProperty('projectStatusId')) {
                obj['projectStatusId'] = ApiClient.convertToType(data['projectStatusId'], 'Number');
            }
            if (data.hasOwnProperty('statusName')) {
                obj['statusName'] = ApiClient.convertToType(data['statusName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} projectStatusId
 */
MozuAppDevContractsProjectStatus.prototype['projectStatusId'] = undefined;

/**
 * @member {String} statusName
 */
MozuAppDevContractsProjectStatus.prototype['statusName'] = undefined;






export default MozuAppDevContractsProjectStatus;

