/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsApplicationTransaction from './MozuAppDevContractsApplicationTransaction';

/**
 * The MozuAppDevContractsApplicationEntitlement model module.
 * @module model/MozuAppDevContractsApplicationEntitlement
 * @version v1
 */
class MozuAppDevContractsApplicationEntitlement {
    /**
     * Constructs a new <code>MozuAppDevContractsApplicationEntitlement</code>.
     * @alias module:model/MozuAppDevContractsApplicationEntitlement
     */
    constructor() { 
        
        MozuAppDevContractsApplicationEntitlement.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsApplicationEntitlement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsApplicationEntitlement} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsApplicationEntitlement} The populated <code>MozuAppDevContractsApplicationEntitlement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsApplicationEntitlement();

            if (data.hasOwnProperty('appKey')) {
                obj['appKey'] = ApiClient.convertToType(data['appKey'], 'String');
            }
            if (data.hasOwnProperty('applicationEntitlementId')) {
                obj['applicationEntitlementId'] = ApiClient.convertToType(data['applicationEntitlementId'], 'Number');
            }
            if (data.hasOwnProperty('packageId')) {
                obj['packageId'] = ApiClient.convertToType(data['packageId'], 'Number');
            }
            if (data.hasOwnProperty('applicationLicenseType')) {
                obj['applicationLicenseType'] = ApiClient.convertToType(data['applicationLicenseType'], 'String');
            }
            if (data.hasOwnProperty('entitlementStatus')) {
                obj['entitlementStatus'] = ApiClient.convertToType(data['entitlementStatus'], 'String');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('siteId')) {
                obj['siteId'] = ApiClient.convertToType(data['siteId'], 'Number');
            }
            if (data.hasOwnProperty('effectiveStartDate')) {
                obj['effectiveStartDate'] = ApiClient.convertToType(data['effectiveStartDate'], 'Date');
            }
            if (data.hasOwnProperty('effectiveEndDate')) {
                obj['effectiveEndDate'] = ApiClient.convertToType(data['effectiveEndDate'], 'Date');
            }
            if (data.hasOwnProperty('applicationTransactions')) {
                obj['applicationTransactions'] = ApiClient.convertToType(data['applicationTransactions'], [MozuAppDevContractsApplicationTransaction]);
            }
            if (data.hasOwnProperty('applicationName')) {
                obj['applicationName'] = ApiClient.convertToType(data['applicationName'], 'String');
            }
            if (data.hasOwnProperty('applicationVersion')) {
                obj['applicationVersion'] = ApiClient.convertToType(data['applicationVersion'], 'String');
            }
            if (data.hasOwnProperty('installedByFirstName')) {
                obj['installedByFirstName'] = ApiClient.convertToType(data['installedByFirstName'], 'String');
            }
            if (data.hasOwnProperty('installedByLastName')) {
                obj['installedByLastName'] = ApiClient.convertToType(data['installedByLastName'], 'String');
            }
            if (data.hasOwnProperty('installedDate')) {
                obj['installedDate'] = ApiClient.convertToType(data['installedDate'], 'Date');
            }
            if (data.hasOwnProperty('packageName')) {
                obj['packageName'] = ApiClient.convertToType(data['packageName'], 'String');
            }
            if (data.hasOwnProperty('tenantName')) {
                obj['tenantName'] = ApiClient.convertToType(data['tenantName'], 'String');
            }
            if (data.hasOwnProperty('applicationStatusId')) {
                obj['applicationStatusId'] = ApiClient.convertToType(data['applicationStatusId'], 'String');
            }
            if (data.hasOwnProperty('applicationId')) {
                obj['applicationId'] = ApiClient.convertToType(data['applicationId'], 'Number');
            }
            if (data.hasOwnProperty('devAccountId')) {
                obj['devAccountId'] = ApiClient.convertToType(data['devAccountId'], 'Number');
            }
            if (data.hasOwnProperty('installedAppsApplicationId')) {
                obj['installedAppsApplicationId'] = ApiClient.convertToType(data['installedAppsApplicationId'], 'String');
            }
            if (data.hasOwnProperty('appOwnerDevAccountId')) {
                obj['appOwnerDevAccountId'] = ApiClient.convertToType(data['appOwnerDevAccountId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} appKey
 */
MozuAppDevContractsApplicationEntitlement.prototype['appKey'] = undefined;

/**
 * @member {Number} applicationEntitlementId
 */
MozuAppDevContractsApplicationEntitlement.prototype['applicationEntitlementId'] = undefined;

/**
 * @member {Number} packageId
 */
MozuAppDevContractsApplicationEntitlement.prototype['packageId'] = undefined;

/**
 * @member {String} applicationLicenseType
 */
MozuAppDevContractsApplicationEntitlement.prototype['applicationLicenseType'] = undefined;

/**
 * @member {String} entitlementStatus
 */
MozuAppDevContractsApplicationEntitlement.prototype['entitlementStatus'] = undefined;

/**
 * @member {Number} tenantId
 */
MozuAppDevContractsApplicationEntitlement.prototype['tenantId'] = undefined;

/**
 * @member {Number} siteId
 */
MozuAppDevContractsApplicationEntitlement.prototype['siteId'] = undefined;

/**
 * @member {Date} effectiveStartDate
 */
MozuAppDevContractsApplicationEntitlement.prototype['effectiveStartDate'] = undefined;

/**
 * @member {Date} effectiveEndDate
 */
MozuAppDevContractsApplicationEntitlement.prototype['effectiveEndDate'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsApplicationTransaction>} applicationTransactions
 */
MozuAppDevContractsApplicationEntitlement.prototype['applicationTransactions'] = undefined;

/**
 * @member {String} applicationName
 */
MozuAppDevContractsApplicationEntitlement.prototype['applicationName'] = undefined;

/**
 * @member {String} applicationVersion
 */
MozuAppDevContractsApplicationEntitlement.prototype['applicationVersion'] = undefined;

/**
 * @member {String} installedByFirstName
 */
MozuAppDevContractsApplicationEntitlement.prototype['installedByFirstName'] = undefined;

/**
 * @member {String} installedByLastName
 */
MozuAppDevContractsApplicationEntitlement.prototype['installedByLastName'] = undefined;

/**
 * @member {Date} installedDate
 */
MozuAppDevContractsApplicationEntitlement.prototype['installedDate'] = undefined;

/**
 * @member {String} packageName
 */
MozuAppDevContractsApplicationEntitlement.prototype['packageName'] = undefined;

/**
 * @member {String} tenantName
 */
MozuAppDevContractsApplicationEntitlement.prototype['tenantName'] = undefined;

/**
 * @member {String} applicationStatusId
 */
MozuAppDevContractsApplicationEntitlement.prototype['applicationStatusId'] = undefined;

/**
 * @member {Number} applicationId
 */
MozuAppDevContractsApplicationEntitlement.prototype['applicationId'] = undefined;

/**
 * @member {Number} devAccountId
 */
MozuAppDevContractsApplicationEntitlement.prototype['devAccountId'] = undefined;

/**
 * @member {String} installedAppsApplicationId
 */
MozuAppDevContractsApplicationEntitlement.prototype['installedAppsApplicationId'] = undefined;

/**
 * @member {Number} appOwnerDevAccountId
 */
MozuAppDevContractsApplicationEntitlement.prototype['appOwnerDevAccountId'] = undefined;






export default MozuAppDevContractsApplicationEntitlement;

