/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsCapabilityType model module.
 * @module model/MozuAppDevContractsCapabilityType
 * @version v1
 */
class MozuAppDevContractsCapabilityType {
    /**
     * Constructs a new <code>MozuAppDevContractsCapabilityType</code>.
     * @alias module:model/MozuAppDevContractsCapabilityType
     */
    constructor() { 
        
        MozuAppDevContractsCapabilityType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsCapabilityType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsCapabilityType} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsCapabilityType} The populated <code>MozuAppDevContractsCapabilityType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsCapabilityType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('capabilityTypeName')) {
                obj['capabilityTypeName'] = ApiClient.convertToType(data['capabilityTypeName'], 'String');
            }
            if (data.hasOwnProperty('capabilityTypeLabel')) {
                obj['capabilityTypeLabel'] = ApiClient.convertToType(data['capabilityTypeLabel'], 'String');
            }
            if (data.hasOwnProperty('apiVersionNumber')) {
                obj['apiVersionNumber'] = ApiClient.convertToType(data['apiVersionNumber'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsCapabilityType.prototype['id'] = undefined;

/**
 * @member {String} capabilityTypeName
 */
MozuAppDevContractsCapabilityType.prototype['capabilityTypeName'] = undefined;

/**
 * @member {String} capabilityTypeLabel
 */
MozuAppDevContractsCapabilityType.prototype['capabilityTypeLabel'] = undefined;

/**
 * @member {String} apiVersionNumber
 */
MozuAppDevContractsCapabilityType.prototype['apiVersionNumber'] = undefined;






export default MozuAppDevContractsCapabilityType;

