/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsAppVersion from './MozuAppDevContractsAppVersion';

/**
 * The MozuAppDevContractsApplicationSummary model module.
 * @module model/MozuAppDevContractsApplicationSummary
 * @version v1
 */
class MozuAppDevContractsApplicationSummary {
    /**
     * Constructs a new <code>MozuAppDevContractsApplicationSummary</code>.
     * @alias module:model/MozuAppDevContractsApplicationSummary
     */
    constructor() { 
        
        MozuAppDevContractsApplicationSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsApplicationSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsApplicationSummary} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsApplicationSummary} The populated <code>MozuAppDevContractsApplicationSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsApplicationSummary();

            if (data.hasOwnProperty('parentName')) {
                obj['parentName'] = ApiClient.convertToType(data['parentName'], 'String');
            }
            if (data.hasOwnProperty('applicationId')) {
                obj['applicationId'] = ApiClient.convertToType(data['applicationId'], 'Number');
            }
            if (data.hasOwnProperty('applicationTypeId')) {
                obj['applicationTypeId'] = ApiClient.convertToType(data['applicationTypeId'], 'Number');
            }
            if (data.hasOwnProperty('releasePackageId')) {
                obj['releasePackageId'] = ApiClient.convertToType(data['releasePackageId'], 'Number');
            }
            if (data.hasOwnProperty('releasePackageName')) {
                obj['releasePackageName'] = ApiClient.convertToType(data['releasePackageName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('applicationNamespace')) {
                obj['applicationNamespace'] = ApiClient.convertToType(data['applicationNamespace'], 'String');
            }
            if (data.hasOwnProperty('applicationVersion')) {
                obj['applicationVersion'] = MozuAppDevContractsAppVersion.constructFromObject(data['applicationVersion']);
            }
            if (data.hasOwnProperty('applicationStatusId')) {
                obj['applicationStatusId'] = ApiClient.convertToType(data['applicationStatusId'], 'Number');
            }
            if (data.hasOwnProperty('appId')) {
                obj['appId'] = ApiClient.convertToType(data['appId'], 'String');
            }
            if (data.hasOwnProperty('applicationStatusName')) {
                obj['applicationStatusName'] = ApiClient.convertToType(data['applicationStatusName'], 'String');
            }
            if (data.hasOwnProperty('hasVersions')) {
                obj['hasVersions'] = ApiClient.convertToType(data['hasVersions'], 'Boolean');
            }
            if (data.hasOwnProperty('appSchemeVersion')) {
                obj['appSchemeVersion'] = ApiClient.convertToType(data['appSchemeVersion'], 'Number');
            }
            if (data.hasOwnProperty('appKey')) {
                obj['appKey'] = ApiClient.convertToType(data['appKey'], 'String');
            }
            if (data.hasOwnProperty('parentAppKey')) {
                obj['parentAppKey'] = ApiClient.convertToType(data['parentAppKey'], 'String');
            }
            if (data.hasOwnProperty('updateParentAppKey')) {
                obj['updateParentAppKey'] = ApiClient.convertToType(data['updateParentAppKey'], 'String');
            }
            if (data.hasOwnProperty('updateAvailable')) {
                obj['updateAvailable'] = ApiClient.convertToType(data['updateAvailable'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} parentName
 */
MozuAppDevContractsApplicationSummary.prototype['parentName'] = undefined;

/**
 * @member {Number} applicationId
 */
MozuAppDevContractsApplicationSummary.prototype['applicationId'] = undefined;

/**
 * @member {Number} applicationTypeId
 */
MozuAppDevContractsApplicationSummary.prototype['applicationTypeId'] = undefined;

/**
 * @member {Number} releasePackageId
 */
MozuAppDevContractsApplicationSummary.prototype['releasePackageId'] = undefined;

/**
 * @member {String} releasePackageName
 */
MozuAppDevContractsApplicationSummary.prototype['releasePackageName'] = undefined;

/**
 * @member {String} name
 */
MozuAppDevContractsApplicationSummary.prototype['name'] = undefined;

/**
 * @member {String} applicationNamespace
 */
MozuAppDevContractsApplicationSummary.prototype['applicationNamespace'] = undefined;

/**
 * @member {module:model/MozuAppDevContractsAppVersion} applicationVersion
 */
MozuAppDevContractsApplicationSummary.prototype['applicationVersion'] = undefined;

/**
 * @member {Number} applicationStatusId
 */
MozuAppDevContractsApplicationSummary.prototype['applicationStatusId'] = undefined;

/**
 * @member {String} appId
 */
MozuAppDevContractsApplicationSummary.prototype['appId'] = undefined;

/**
 * @member {String} applicationStatusName
 */
MozuAppDevContractsApplicationSummary.prototype['applicationStatusName'] = undefined;

/**
 * @member {Boolean} hasVersions
 */
MozuAppDevContractsApplicationSummary.prototype['hasVersions'] = undefined;

/**
 * @member {Number} appSchemeVersion
 */
MozuAppDevContractsApplicationSummary.prototype['appSchemeVersion'] = undefined;

/**
 * @member {String} appKey
 */
MozuAppDevContractsApplicationSummary.prototype['appKey'] = undefined;

/**
 * @member {String} parentAppKey
 */
MozuAppDevContractsApplicationSummary.prototype['parentAppKey'] = undefined;

/**
 * @member {String} updateParentAppKey
 */
MozuAppDevContractsApplicationSummary.prototype['updateParentAppKey'] = undefined;

/**
 * @member {Boolean} updateAvailable
 */
MozuAppDevContractsApplicationSummary.prototype['updateAvailable'] = undefined;






export default MozuAppDevContractsApplicationSummary;

