/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsAssetFileMetadata from './MozuAppDevContractsAssetFileMetadata';

/**
 * The MozuAppDevContractsAssetFileMetadataNode model module.
 * @module model/MozuAppDevContractsAssetFileMetadataNode
 * @version v1
 */
class MozuAppDevContractsAssetFileMetadataNode {
    /**
     * Constructs a new <code>MozuAppDevContractsAssetFileMetadataNode</code>.
     * @alias module:model/MozuAppDevContractsAssetFileMetadataNode
     */
    constructor() { 
        
        MozuAppDevContractsAssetFileMetadataNode.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsAssetFileMetadataNode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsAssetFileMetadataNode} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsAssetFileMetadataNode} The populated <code>MozuAppDevContractsAssetFileMetadataNode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsAssetFileMetadataNode();

            if (data.hasOwnProperty('fullPath')) {
                obj['fullPath'] = ApiClient.convertToType(data['fullPath'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parentPath')) {
                obj['parentPath'] = ApiClient.convertToType(data['parentPath'], 'String');
            }
            if (data.hasOwnProperty('isFolder')) {
                obj['isFolder'] = ApiClient.convertToType(data['isFolder'], 'Boolean');
            }
            if (data.hasOwnProperty('hasChildren')) {
                obj['hasChildren'] = ApiClient.convertToType(data['hasChildren'], 'Boolean');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = MozuAppDevContractsAssetFileMetadata.constructFromObject(data['content']);
            }
            if (data.hasOwnProperty('children')) {
                obj['children'] = ApiClient.convertToType(data['children'], [MozuAppDevContractsAssetFileMetadataNode]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} fullPath
 */
MozuAppDevContractsAssetFileMetadataNode.prototype['fullPath'] = undefined;

/**
 * @member {String} name
 */
MozuAppDevContractsAssetFileMetadataNode.prototype['name'] = undefined;

/**
 * @member {String} parentPath
 */
MozuAppDevContractsAssetFileMetadataNode.prototype['parentPath'] = undefined;

/**
 * @member {Boolean} isFolder
 */
MozuAppDevContractsAssetFileMetadataNode.prototype['isFolder'] = undefined;

/**
 * @member {Boolean} hasChildren
 */
MozuAppDevContractsAssetFileMetadataNode.prototype['hasChildren'] = undefined;

/**
 * @member {module:model/MozuAppDevContractsAssetFileMetadata} content
 */
MozuAppDevContractsAssetFileMetadataNode.prototype['content'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsAssetFileMetadataNode>} children
 */
MozuAppDevContractsAssetFileMetadataNode.prototype['children'] = undefined;






export default MozuAppDevContractsAssetFileMetadataNode;

