/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuCoreApiContractsProvisioningCloneTenantCatalogPairing from './MozuCoreApiContractsProvisioningCloneTenantCatalogPairing';

/**
 * The MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing model module.
 * @module model/MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing
 * @version v1
 */
class MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing {
    /**
     * Constructs a new <code>MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing</code>.
     * @alias module:model/MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing
     */
    constructor() { 
        
        MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing} obj Optional instance to populate.
     * @return {module:model/MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing} The populated <code>MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing();

            if (data.hasOwnProperty('sourceMasterCatalogId')) {
                obj['sourceMasterCatalogId'] = ApiClient.convertToType(data['sourceMasterCatalogId'], 'Number');
            }
            if (data.hasOwnProperty('targetMasterCatalogId')) {
                obj['targetMasterCatalogId'] = ApiClient.convertToType(data['targetMasterCatalogId'], 'Number');
            }
            if (data.hasOwnProperty('catalogPairings')) {
                obj['catalogPairings'] = ApiClient.convertToType(data['catalogPairings'], [MozuCoreApiContractsProvisioningCloneTenantCatalogPairing]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} sourceMasterCatalogId
 */
MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing.prototype['sourceMasterCatalogId'] = undefined;

/**
 * @member {Number} targetMasterCatalogId
 */
MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing.prototype['targetMasterCatalogId'] = undefined;

/**
 * @member {Array.<module:model/MozuCoreApiContractsProvisioningCloneTenantCatalogPairing>} catalogPairings
 */
MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing.prototype['catalogPairings'] = undefined;






export default MozuCoreApiContractsProvisioningCloneTenantMasterCatalogPairing;

