/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsApiVersionNumber from './MozuAppDevContractsApiVersionNumber';

/**
 * The MozuAppDevContractsApiVersionRequest model module.
 * @module model/MozuAppDevContractsApiVersionRequest
 * @version v1
 */
class MozuAppDevContractsApiVersionRequest {
    /**
     * Constructs a new <code>MozuAppDevContractsApiVersionRequest</code>.
     * @alias module:model/MozuAppDevContractsApiVersionRequest
     */
    constructor() { 
        
        MozuAppDevContractsApiVersionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsApiVersionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsApiVersionRequest} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsApiVersionRequest} The populated <code>MozuAppDevContractsApiVersionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsApiVersionRequest();

            if (data.hasOwnProperty('applicationId')) {
                obj['applicationId'] = ApiClient.convertToType(data['applicationId'], 'Number');
            }
            if (data.hasOwnProperty('apiVersionNumberFrom')) {
                obj['apiVersionNumberFrom'] = MozuAppDevContractsApiVersionNumber.constructFromObject(data['apiVersionNumberFrom']);
            }
            if (data.hasOwnProperty('apiVersionNumberTo')) {
                obj['apiVersionNumberTo'] = MozuAppDevContractsApiVersionNumber.constructFromObject(data['apiVersionNumberTo']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} applicationId
 */
MozuAppDevContractsApiVersionRequest.prototype['applicationId'] = undefined;

/**
 * @member {module:model/MozuAppDevContractsApiVersionNumber} apiVersionNumberFrom
 */
MozuAppDevContractsApiVersionRequest.prototype['apiVersionNumberFrom'] = undefined;

/**
 * @member {module:model/MozuAppDevContractsApiVersionNumber} apiVersionNumberTo
 */
MozuAppDevContractsApiVersionRequest.prototype['apiVersionNumberTo'] = undefined;






export default MozuAppDevContractsApiVersionRequest;

