/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsApplicationCapability model module.
 * @module model/MozuAppDevContractsApplicationCapability
 * @version v1
 */
class MozuAppDevContractsApplicationCapability {
    /**
     * Constructs a new <code>MozuAppDevContractsApplicationCapability</code>.
     * @alias module:model/MozuAppDevContractsApplicationCapability
     */
    constructor() { 
        
        MozuAppDevContractsApplicationCapability.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsApplicationCapability</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsApplicationCapability} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsApplicationCapability} The populated <code>MozuAppDevContractsApplicationCapability</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsApplicationCapability();

            if (data.hasOwnProperty('applicationCapabilityId')) {
                obj['applicationCapabilityId'] = ApiClient.convertToType(data['applicationCapabilityId'], 'Number');
            }
            if (data.hasOwnProperty('capabilityTypeContractId')) {
                obj['capabilityTypeContractId'] = ApiClient.convertToType(data['capabilityTypeContractId'], 'Number');
            }
            if (data.hasOwnProperty('applicationEndPoint')) {
                obj['applicationEndPoint'] = ApiClient.convertToType(data['applicationEndPoint'], 'String');
            }
            if (data.hasOwnProperty('applicationCapabilityTypeId')) {
                obj['applicationCapabilityTypeId'] = ApiClient.convertToType(data['applicationCapabilityTypeId'], 'Number');
            }
            if (data.hasOwnProperty('packageId')) {
                obj['packageId'] = ApiClient.convertToType(data['packageId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} applicationCapabilityId
 */
MozuAppDevContractsApplicationCapability.prototype['applicationCapabilityId'] = undefined;

/**
 * @member {Number} capabilityTypeContractId
 */
MozuAppDevContractsApplicationCapability.prototype['capabilityTypeContractId'] = undefined;

/**
 * @member {String} applicationEndPoint
 */
MozuAppDevContractsApplicationCapability.prototype['applicationEndPoint'] = undefined;

/**
 * @member {Number} applicationCapabilityTypeId
 */
MozuAppDevContractsApplicationCapability.prototype['applicationCapabilityTypeId'] = undefined;

/**
 * @member {Number} packageId
 */
MozuAppDevContractsApplicationCapability.prototype['packageId'] = undefined;






export default MozuAppDevContractsApplicationCapability;

