/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuCoreApiContractsContact from './MozuCoreApiContractsContact';

/**
 * The MozuAppDevContractsDeveloperContact model module.
 * @module model/MozuAppDevContractsDeveloperContact
 * @version v1
 */
class MozuAppDevContractsDeveloperContact {
    /**
     * Constructs a new <code>MozuAppDevContractsDeveloperContact</code>.
     * @alias module:model/MozuAppDevContractsDeveloperContact
     */
    constructor() { 
        
        MozuAppDevContractsDeveloperContact.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsDeveloperContact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsDeveloperContact} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsDeveloperContact} The populated <code>MozuAppDevContractsDeveloperContact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsDeveloperContact();

            if (data.hasOwnProperty('contact')) {
                obj['contact'] = MozuCoreApiContractsContact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MozuCoreApiContractsContact} contact
 */
MozuAppDevContractsDeveloperContact.prototype['contact'] = undefined;

/**
 * @member {String} type
 */
MozuAppDevContractsDeveloperContact.prototype['type'] = undefined;






export default MozuAppDevContractsDeveloperContact;

