/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsProjectUser model module.
 * @module model/MozuAppDevContractsProjectUser
 * @version v1
 */
class MozuAppDevContractsProjectUser {
    /**
     * Constructs a new <code>MozuAppDevContractsProjectUser</code>.
     * @alias module:model/MozuAppDevContractsProjectUser
     */
    constructor() { 
        
        MozuAppDevContractsProjectUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsProjectUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsProjectUser} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsProjectUser} The populated <code>MozuAppDevContractsProjectUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsProjectUser();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'Number');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('developerId')) {
                obj['developerId'] = ApiClient.convertToType(data['developerId'], 'Number');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsProjectUser.prototype['id'] = undefined;

/**
 * @member {Number} projectId
 */
MozuAppDevContractsProjectUser.prototype['projectId'] = undefined;

/**
 * @member {String} userId
 */
MozuAppDevContractsProjectUser.prototype['userId'] = undefined;

/**
 * @member {Number} developerId
 */
MozuAppDevContractsProjectUser.prototype['developerId'] = undefined;

/**
 * @member {String} userName
 */
MozuAppDevContractsProjectUser.prototype['userName'] = undefined;






export default MozuAppDevContractsProjectUser;

