/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsPublicRenameInfo model module.
 * @module model/MozuAppDevContractsPublicRenameInfo
 * @version v1
 */
class MozuAppDevContractsPublicRenameInfo {
    /**
     * Constructs a new <code>MozuAppDevContractsPublicRenameInfo</code>.
     * @alias module:model/MozuAppDevContractsPublicRenameInfo
     */
    constructor() { 
        
        MozuAppDevContractsPublicRenameInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsPublicRenameInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsPublicRenameInfo} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsPublicRenameInfo} The populated <code>MozuAppDevContractsPublicRenameInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsPublicRenameInfo();

            if (data.hasOwnProperty('oldFullPath')) {
                obj['oldFullPath'] = ApiClient.convertToType(data['oldFullPath'], 'String');
            }
            if (data.hasOwnProperty('newFullPath')) {
                obj['newFullPath'] = ApiClient.convertToType(data['newFullPath'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} oldFullPath
 */
MozuAppDevContractsPublicRenameInfo.prototype['oldFullPath'] = undefined;

/**
 * @member {String} newFullPath
 */
MozuAppDevContractsPublicRenameInfo.prototype['newFullPath'] = undefined;






export default MozuAppDevContractsPublicRenameInfo;

