/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuCoreApiContractsAuditInfo model module.
 * @module model/MozuCoreApiContractsAuditInfo
 * @version v1
 */
class MozuCoreApiContractsAuditInfo {
    /**
     * Constructs a new <code>MozuCoreApiContractsAuditInfo</code>.
     * @alias module:model/MozuCoreApiContractsAuditInfo
     */
    constructor() { 
        
        MozuCoreApiContractsAuditInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreApiContractsAuditInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreApiContractsAuditInfo} obj Optional instance to populate.
     * @return {module:model/MozuCoreApiContractsAuditInfo} The populated <code>MozuCoreApiContractsAuditInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreApiContractsAuditInfo();

            if (data.hasOwnProperty('updateDate')) {
                obj['updateDate'] = ApiClient.convertToType(data['updateDate'], 'Date');
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'Date');
            }
            if (data.hasOwnProperty('updateBy')) {
                obj['updateBy'] = ApiClient.convertToType(data['updateBy'], 'String');
            }
            if (data.hasOwnProperty('createBy')) {
                obj['createBy'] = ApiClient.convertToType(data['createBy'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} updateDate
 */
MozuCoreApiContractsAuditInfo.prototype['updateDate'] = undefined;

/**
 * @member {Date} createDate
 */
MozuCoreApiContractsAuditInfo.prototype['createDate'] = undefined;

/**
 * @member {String} updateBy
 */
MozuCoreApiContractsAuditInfo.prototype['updateBy'] = undefined;

/**
 * @member {String} createBy
 */
MozuCoreApiContractsAuditInfo.prototype['createBy'] = undefined;






export default MozuCoreApiContractsAuditInfo;

