/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuCoreApiContractsAuditInfo from './MozuCoreApiContractsAuditInfo';

/**
 * The MozuAppDevContractsDevStoreTemplate model module.
 * @module model/MozuAppDevContractsDevStoreTemplate
 * @version v1
 */
class MozuAppDevContractsDevStoreTemplate {
    /**
     * Constructs a new <code>MozuAppDevContractsDevStoreTemplate</code>.
     * @alias module:model/MozuAppDevContractsDevStoreTemplate
     */
    constructor() { 
        
        MozuAppDevContractsDevStoreTemplate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsDevStoreTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsDevStoreTemplate} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsDevStoreTemplate} The populated <code>MozuAppDevContractsDevStoreTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsDevStoreTemplate();

            if (data.hasOwnProperty('devStoreTemplateId')) {
                obj['devStoreTemplateId'] = ApiClient.convertToType(data['devStoreTemplateId'], 'Number');
            }
            if (data.hasOwnProperty('templateName')) {
                obj['templateName'] = ApiClient.convertToType(data['templateName'], 'String');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('templateDescription')) {
                obj['templateDescription'] = ApiClient.convertToType(data['templateDescription'], 'String');
            }
            if (data.hasOwnProperty('heroImage')) {
                obj['heroImage'] = ApiClient.convertToType(data['heroImage'], 'String');
            }
            if (data.hasOwnProperty('auditInfo')) {
                obj['auditInfo'] = MozuCoreApiContractsAuditInfo.constructFromObject(data['auditInfo']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} devStoreTemplateId
 */
MozuAppDevContractsDevStoreTemplate.prototype['devStoreTemplateId'] = undefined;

/**
 * @member {String} templateName
 */
MozuAppDevContractsDevStoreTemplate.prototype['templateName'] = undefined;

/**
 * @member {Number} tenantId
 */
MozuAppDevContractsDevStoreTemplate.prototype['tenantId'] = undefined;

/**
 * @member {String} templateDescription
 */
MozuAppDevContractsDevStoreTemplate.prototype['templateDescription'] = undefined;

/**
 * @member {String} heroImage
 */
MozuAppDevContractsDevStoreTemplate.prototype['heroImage'] = undefined;

/**
 * @member {module:model/MozuCoreApiContractsAuditInfo} auditInfo
 */
MozuAppDevContractsDevStoreTemplate.prototype['auditInfo'] = undefined;






export default MozuAppDevContractsDevStoreTemplate;

