/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuCoreMessagingContractsMessagePublishingContext model module.
 * @module model/MozuCoreMessagingContractsMessagePublishingContext
 * @version v1
 */
class MozuCoreMessagingContractsMessagePublishingContext {
    /**
     * Constructs a new <code>MozuCoreMessagingContractsMessagePublishingContext</code>.
     * @alias module:model/MozuCoreMessagingContractsMessagePublishingContext
     */
    constructor() { 
        
        MozuCoreMessagingContractsMessagePublishingContext.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreMessagingContractsMessagePublishingContext</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreMessagingContractsMessagePublishingContext} obj Optional instance to populate.
     * @return {module:model/MozuCoreMessagingContractsMessagePublishingContext} The populated <code>MozuCoreMessagingContractsMessagePublishingContext</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreMessagingContractsMessagePublishingContext();

            if (data.hasOwnProperty('siteId')) {
                obj['siteId'] = ApiClient.convertToType(data['siteId'], 'Number');
            }
            if (data.hasOwnProperty('catalogId')) {
                obj['catalogId'] = ApiClient.convertToType(data['catalogId'], 'Number');
            }
            if (data.hasOwnProperty('masterCatalogId')) {
                obj['masterCatalogId'] = ApiClient.convertToType(data['masterCatalogId'], 'Number');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('localeCode')) {
                obj['localeCode'] = ApiClient.convertToType(data['localeCode'], 'String');
            }
            if (data.hasOwnProperty('currencyCode')) {
                obj['currencyCode'] = ApiClient.convertToType(data['currencyCode'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('customerId')) {
                obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
            }
            if (data.hasOwnProperty('visitId')) {
                obj['visitId'] = ApiClient.convertToType(data['visitId'], 'String');
            }
            if (data.hasOwnProperty('initiatingAppId')) {
                obj['initiatingAppId'] = ApiClient.convertToType(data['initiatingAppId'], 'String');
            }
            if (data.hasOwnProperty('correlationId')) {
                obj['correlationId'] = ApiClient.convertToType(data['correlationId'], 'String');
            }
            if (data.hasOwnProperty('isTest')) {
                obj['isTest'] = ApiClient.convertToType(data['isTest'], 'Boolean');
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'Date');
            }
            if (data.hasOwnProperty('createBy')) {
                obj['createBy'] = ApiClient.convertToType(data['createBy'], 'String');
            }
            if (data.hasOwnProperty('dataViewMode')) {
                obj['dataViewMode'] = ApiClient.convertToType(data['dataViewMode'], 'Number');
            }
            if (data.hasOwnProperty('mozuInstanceId')) {
                obj['mozuInstanceId'] = ApiClient.convertToType(data['mozuInstanceId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} siteId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['siteId'] = undefined;

/**
 * @member {Number} catalogId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['catalogId'] = undefined;

/**
 * @member {Number} masterCatalogId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['masterCatalogId'] = undefined;

/**
 * @member {Number} tenantId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['tenantId'] = undefined;

/**
 * @member {String} localeCode
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['localeCode'] = undefined;

/**
 * @member {String} currencyCode
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['currencyCode'] = undefined;

/**
 * @member {String} userId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['userId'] = undefined;

/**
 * @member {String} customerId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['customerId'] = undefined;

/**
 * @member {String} visitId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['visitId'] = undefined;

/**
 * @member {String} initiatingAppId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['initiatingAppId'] = undefined;

/**
 * @member {String} correlationId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['correlationId'] = undefined;

/**
 * @member {Boolean} isTest
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['isTest'] = undefined;

/**
 * @member {Date} createDate
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['createDate'] = undefined;

/**
 * @member {String} createBy
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['createBy'] = undefined;

/**
 * @member {Number} dataViewMode
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['dataViewMode'] = undefined;

/**
 * @member {String} mozuInstanceId
 */
MozuCoreMessagingContractsMessagePublishingContext.prototype['mozuInstanceId'] = undefined;






export default MozuCoreMessagingContractsMessagePublishingContext;

