/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuCoreApiContractsAuditInfo from './MozuCoreApiContractsAuditInfo';

/**
 * The MozuAppDevContractsAssetFileMetadata model module.
 * @module model/MozuAppDevContractsAssetFileMetadata
 * @version v1
 */
class MozuAppDevContractsAssetFileMetadata {
    /**
     * Constructs a new <code>MozuAppDevContractsAssetFileMetadata</code>.
     * @alias module:model/MozuAppDevContractsAssetFileMetadata
     */
    constructor() { 
        
        MozuAppDevContractsAssetFileMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsAssetFileMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsAssetFileMetadata} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsAssetFileMetadata} The populated <code>MozuAppDevContractsAssetFileMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsAssetFileMetadata();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('checkSum')) {
                obj['checkSum'] = ApiClient.convertToType(data['checkSum'], 'String');
            }
            if (data.hasOwnProperty('sizeInBytes')) {
                obj['sizeInBytes'] = ApiClient.convertToType(data['sizeInBytes'], 'Number');
            }
            if (data.hasOwnProperty('isFolder')) {
                obj['isFolder'] = ApiClient.convertToType(data['isFolder'], 'Boolean');
            }
            if (data.hasOwnProperty('auditInfo')) {
                obj['auditInfo'] = MozuCoreApiContractsAuditInfo.constructFromObject(data['auditInfo']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
MozuAppDevContractsAssetFileMetadata.prototype['id'] = undefined;

/**
 * @member {String} type
 */
MozuAppDevContractsAssetFileMetadata.prototype['type'] = undefined;

/**
 * @member {String} path
 */
MozuAppDevContractsAssetFileMetadata.prototype['path'] = undefined;

/**
 * @member {String} checkSum
 */
MozuAppDevContractsAssetFileMetadata.prototype['checkSum'] = undefined;

/**
 * @member {Number} sizeInBytes
 */
MozuAppDevContractsAssetFileMetadata.prototype['sizeInBytes'] = undefined;

/**
 * @member {Boolean} isFolder
 */
MozuAppDevContractsAssetFileMetadata.prototype['isFolder'] = undefined;

/**
 * @member {module:model/MozuCoreApiContractsAuditInfo} auditInfo
 */
MozuAppDevContractsAssetFileMetadata.prototype['auditInfo'] = undefined;






export default MozuAppDevContractsAssetFileMetadata;

