/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsOrderCapabilityType model module.
 * @module model/MozuAppDevContractsOrderCapabilityType
 * @version v1
 */
class MozuAppDevContractsOrderCapabilityType {
    /**
     * Constructs a new <code>MozuAppDevContractsOrderCapabilityType</code>.
     * @alias module:model/MozuAppDevContractsOrderCapabilityType
     */
    constructor() { 
        
        MozuAppDevContractsOrderCapabilityType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsOrderCapabilityType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsOrderCapabilityType} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsOrderCapabilityType} The populated <code>MozuAppDevContractsOrderCapabilityType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsOrderCapabilityType();

            if (data.hasOwnProperty('capabilityTypeName')) {
                obj['capabilityTypeName'] = ApiClient.convertToType(data['capabilityTypeName'], 'String');
            }
            if (data.hasOwnProperty('isImplemented')) {
                obj['isImplemented'] = ApiClient.convertToType(data['isImplemented'], 'Boolean');
            }
            if (data.hasOwnProperty('isInitializedByDefault')) {
                obj['isInitializedByDefault'] = ApiClient.convertToType(data['isInitializedByDefault'], 'Boolean');
            }
            if (data.hasOwnProperty('endpoint')) {
                obj['endpoint'] = ApiClient.convertToType(data['endpoint'], 'String');
            }
            if (data.hasOwnProperty('packageId')) {
                obj['packageId'] = ApiClient.convertToType(data['packageId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} capabilityTypeName
 */
MozuAppDevContractsOrderCapabilityType.prototype['capabilityTypeName'] = undefined;

/**
 * @member {Boolean} isImplemented
 */
MozuAppDevContractsOrderCapabilityType.prototype['isImplemented'] = undefined;

/**
 * @member {Boolean} isInitializedByDefault
 */
MozuAppDevContractsOrderCapabilityType.prototype['isInitializedByDefault'] = undefined;

/**
 * @member {String} endpoint
 */
MozuAppDevContractsOrderCapabilityType.prototype['endpoint'] = undefined;

/**
 * @member {Number} packageId
 */
MozuAppDevContractsOrderCapabilityType.prototype['packageId'] = undefined;






export default MozuAppDevContractsOrderCapabilityType;

