/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsSite model module.
 * @module model/MozuAppDevContractsSite
 * @version v1
 */
class MozuAppDevContractsSite {
    /**
     * Constructs a new <code>MozuAppDevContractsSite</code>.
     * @alias module:model/MozuAppDevContractsSite
     */
    constructor() { 
        
        MozuAppDevContractsSite.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsSite</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsSite} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsSite} The populated <code>MozuAppDevContractsSite</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsSite();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('masterCatalogId')) {
                obj['masterCatalogId'] = ApiClient.convertToType(data['masterCatalogId'], 'Number');
            }
            if (data.hasOwnProperty('catalogId')) {
                obj['catalogId'] = ApiClient.convertToType(data['catalogId'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('defaultLocaleCode')) {
                obj['defaultLocaleCode'] = ApiClient.convertToType(data['defaultLocaleCode'], 'String');
            }
            if (data.hasOwnProperty('defaultCurrencyCode')) {
                obj['defaultCurrencyCode'] = ApiClient.convertToType(data['defaultCurrencyCode'], 'String');
            }
            if (data.hasOwnProperty('isMozuRendered')) {
                obj['isMozuRendered'] = ApiClient.convertToType(data['isMozuRendered'], 'Boolean');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsSite.prototype['id'] = undefined;

/**
 * @member {Number} tenantId
 */
MozuAppDevContractsSite.prototype['tenantId'] = undefined;

/**
 * @member {Number} masterCatalogId
 */
MozuAppDevContractsSite.prototype['masterCatalogId'] = undefined;

/**
 * @member {Number} catalogId
 */
MozuAppDevContractsSite.prototype['catalogId'] = undefined;

/**
 * @member {String} name
 */
MozuAppDevContractsSite.prototype['name'] = undefined;

/**
 * @member {String} countryCode
 */
MozuAppDevContractsSite.prototype['countryCode'] = undefined;

/**
 * @member {String} defaultLocaleCode
 */
MozuAppDevContractsSite.prototype['defaultLocaleCode'] = undefined;

/**
 * @member {String} defaultCurrencyCode
 */
MozuAppDevContractsSite.prototype['defaultCurrencyCode'] = undefined;

/**
 * @member {Boolean} isMozuRendered
 */
MozuAppDevContractsSite.prototype['isMozuRendered'] = undefined;

/**
 * @member {String} domain
 */
MozuAppDevContractsSite.prototype['domain'] = undefined;






export default MozuAppDevContractsSite;

