/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsTypeItem from './MozuAppDevContractsTypeItem';
import MozuAppDevContractsValidationItem from './MozuAppDevContractsValidationItem';

/**
 * The MozuAppDevContractsTypeItems model module.
 * @module model/MozuAppDevContractsTypeItems
 * @version v1
 */
class MozuAppDevContractsTypeItems {
    /**
     * Constructs a new <code>MozuAppDevContractsTypeItems</code>.
     * @alias module:model/MozuAppDevContractsTypeItems
     */
    constructor() { 
        
        MozuAppDevContractsTypeItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsTypeItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsTypeItems} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsTypeItems} The populated <code>MozuAppDevContractsTypeItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsTypeItems();

            if (data.hasOwnProperty('selected')) {
                obj['selected'] = MozuAppDevContractsTypeItem.constructFromObject(data['selected']);
            }
            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], [MozuAppDevContractsTypeItem]);
            }
            if (data.hasOwnProperty('validationItems')) {
                obj['validationItems'] = ApiClient.convertToType(data['validationItems'], [MozuAppDevContractsValidationItem]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MozuAppDevContractsTypeItem} selected
 */
MozuAppDevContractsTypeItems.prototype['selected'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsTypeItem>} available
 */
MozuAppDevContractsTypeItems.prototype['available'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsValidationItem>} validationItems
 */
MozuAppDevContractsTypeItems.prototype['validationItems'] = undefined;






export default MozuAppDevContractsTypeItems;

