/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsDashboardContent model module.
 * @module model/MozuAppDevContractsDashboardContent
 * @version v1
 */
class MozuAppDevContractsDashboardContent {
    /**
     * Constructs a new <code>MozuAppDevContractsDashboardContent</code>.
     * @alias module:model/MozuAppDevContractsDashboardContent
     */
    constructor() { 
        
        MozuAppDevContractsDashboardContent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsDashboardContent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsDashboardContent} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsDashboardContent} The populated <code>MozuAppDevContractsDashboardContent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsDashboardContent();

            if (data.hasOwnProperty('dashboardContentId')) {
                obj['dashboardContentId'] = ApiClient.convertToType(data['dashboardContentId'], 'Number');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('contentLink')) {
                obj['contentLink'] = ApiClient.convertToType(data['contentLink'], 'String');
            }
            if (data.hasOwnProperty('contentTitle')) {
                obj['contentTitle'] = ApiClient.convertToType(data['contentTitle'], 'String');
            }
            if (data.hasOwnProperty('contentSequence')) {
                obj['contentSequence'] = ApiClient.convertToType(data['contentSequence'], 'Number');
            }
            if (data.hasOwnProperty('dashboardContentTypeId')) {
                obj['dashboardContentTypeId'] = ApiClient.convertToType(data['dashboardContentTypeId'], 'Number');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], 'String');
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} dashboardContentId
 */
MozuAppDevContractsDashboardContent.prototype['dashboardContentId'] = undefined;

/**
 * @member {String} content
 */
MozuAppDevContractsDashboardContent.prototype['content'] = undefined;

/**
 * @member {String} contentLink
 */
MozuAppDevContractsDashboardContent.prototype['contentLink'] = undefined;

/**
 * @member {String} contentTitle
 */
MozuAppDevContractsDashboardContent.prototype['contentTitle'] = undefined;

/**
 * @member {Number} contentSequence
 */
MozuAppDevContractsDashboardContent.prototype['contentSequence'] = undefined;

/**
 * @member {Number} dashboardContentTypeId
 */
MozuAppDevContractsDashboardContent.prototype['dashboardContentTypeId'] = undefined;

/**
 * @member {String} tags
 */
MozuAppDevContractsDashboardContent.prototype['tags'] = undefined;

/**
 * @member {Date} createDate
 */
MozuAppDevContractsDashboardContent.prototype['createDate'] = undefined;






export default MozuAppDevContractsDashboardContent;

