/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuCoreApiContractsProvisioningDeleteCatalogRequest model module.
 * @module model/MozuCoreApiContractsProvisioningDeleteCatalogRequest
 * @version v1
 */
class MozuCoreApiContractsProvisioningDeleteCatalogRequest {
    /**
     * Constructs a new <code>MozuCoreApiContractsProvisioningDeleteCatalogRequest</code>.
     * @alias module:model/MozuCoreApiContractsProvisioningDeleteCatalogRequest
     */
    constructor() { 
        
        MozuCoreApiContractsProvisioningDeleteCatalogRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreApiContractsProvisioningDeleteCatalogRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreApiContractsProvisioningDeleteCatalogRequest} obj Optional instance to populate.
     * @return {module:model/MozuCoreApiContractsProvisioningDeleteCatalogRequest} The populated <code>MozuCoreApiContractsProvisioningDeleteCatalogRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreApiContractsProvisioningDeleteCatalogRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('masterCatalogId')) {
                obj['masterCatalogId'] = ApiClient.convertToType(data['masterCatalogId'], 'Number');
            }
            if (data.hasOwnProperty('catalogId')) {
                obj['catalogId'] = ApiClient.convertToType(data['catalogId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} tenantId
 */
MozuCoreApiContractsProvisioningDeleteCatalogRequest.prototype['tenantId'] = undefined;

/**
 * @member {Number} masterCatalogId
 */
MozuCoreApiContractsProvisioningDeleteCatalogRequest.prototype['masterCatalogId'] = undefined;

/**
 * @member {Number} catalogId
 */
MozuCoreApiContractsProvisioningDeleteCatalogRequest.prototype['catalogId'] = undefined;






export default MozuCoreApiContractsProvisioningDeleteCatalogRequest;

