/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsOauthAuthRequest model module.
 * @module model/MozuAppDevContractsOauthAuthRequest
 * @version v1
 */
class MozuAppDevContractsOauthAuthRequest {
    /**
     * Constructs a new <code>MozuAppDevContractsOauthAuthRequest</code>.
     * @alias module:model/MozuAppDevContractsOauthAuthRequest
     */
    constructor() { 
        
        MozuAppDevContractsOauthAuthRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsOauthAuthRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsOauthAuthRequest} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsOauthAuthRequest} The populated <code>MozuAppDevContractsOauthAuthRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsOauthAuthRequest();

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
            if (data.hasOwnProperty('refresh_token')) {
                obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
            }
            if (data.hasOwnProperty('grant_type')) {
                obj['grant_type'] = ApiClient.convertToType(data['grant_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} client_id
 */
MozuAppDevContractsOauthAuthRequest.prototype['client_id'] = undefined;

/**
 * @member {String} client_secret
 */
MozuAppDevContractsOauthAuthRequest.prototype['client_secret'] = undefined;

/**
 * @member {String} refresh_token
 */
MozuAppDevContractsOauthAuthRequest.prototype['refresh_token'] = undefined;

/**
 * @member {String} grant_type
 */
MozuAppDevContractsOauthAuthRequest.prototype['grant_type'] = undefined;






export default MozuAppDevContractsOauthAuthRequest;

