/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsAttributeSubscription model module.
 * @module model/MozuAppDevContractsAttributeSubscription
 * @version v1
 */
class MozuAppDevContractsAttributeSubscription {
    /**
     * Constructs a new <code>MozuAppDevContractsAttributeSubscription</code>.
     * @alias module:model/MozuAppDevContractsAttributeSubscription
     */
    constructor() { 
        
        MozuAppDevContractsAttributeSubscription.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsAttributeSubscription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsAttributeSubscription} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsAttributeSubscription} The populated <code>MozuAppDevContractsAttributeSubscription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsAttributeSubscription();

            if (data.hasOwnProperty('attributeFqnList')) {
                obj['attributeFqnList'] = ApiClient.convertToType(data['attributeFqnList'], ['String']);
            }
            if (data.hasOwnProperty('includesBaseAttributeGrouping')) {
                obj['includesBaseAttributeGrouping'] = ApiClient.convertToType(data['includesBaseAttributeGrouping'], 'Boolean');
            }
            if (data.hasOwnProperty('subsystem')) {
                obj['subsystem'] = ApiClient.convertToType(data['subsystem'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} attributeFqnList
 */
MozuAppDevContractsAttributeSubscription.prototype['attributeFqnList'] = undefined;

/**
 * @member {Boolean} includesBaseAttributeGrouping
 */
MozuAppDevContractsAttributeSubscription.prototype['includesBaseAttributeGrouping'] = undefined;

/**
 * @member {String} subsystem
 */
MozuAppDevContractsAttributeSubscription.prototype['subsystem'] = undefined;






export default MozuAppDevContractsAttributeSubscription;

