/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsDevAccountProdTenant from './MozuAppDevContractsDevAccountProdTenant';

/**
 * The MozuAppDevContractsProductionTenant model module.
 * @module model/MozuAppDevContractsProductionTenant
 * @version v1
 */
class MozuAppDevContractsProductionTenant {
    /**
     * Constructs a new <code>MozuAppDevContractsProductionTenant</code>.
     * @alias module:model/MozuAppDevContractsProductionTenant
     */
    constructor() { 
        
        MozuAppDevContractsProductionTenant.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsProductionTenant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsProductionTenant} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsProductionTenant} The populated <code>MozuAppDevContractsProductionTenant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsProductionTenant();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('clientName')) {
                obj['clientName'] = ApiClient.convertToType(data['clientName'], 'String');
            }
            if (data.hasOwnProperty('devAccountProdTenants')) {
                obj['devAccountProdTenants'] = ApiClient.convertToType(data['devAccountProdTenants'], [MozuAppDevContractsDevAccountProdTenant]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsProductionTenant.prototype['id'] = undefined;

/**
 * @member {String} name
 */
MozuAppDevContractsProductionTenant.prototype['name'] = undefined;

/**
 * @member {String} clientName
 */
MozuAppDevContractsProductionTenant.prototype['clientName'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsDevAccountProdTenant>} devAccountProdTenants
 */
MozuAppDevContractsProductionTenant.prototype['devAccountProdTenants'] = undefined;






export default MozuAppDevContractsProductionTenant;

