/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsProjectTenant model module.
 * @module model/MozuAppDevContractsProjectTenant
 * @version v1
 */
class MozuAppDevContractsProjectTenant {
    /**
     * Constructs a new <code>MozuAppDevContractsProjectTenant</code>.
     * @alias module:model/MozuAppDevContractsProjectTenant
     */
    constructor() { 
        
        MozuAppDevContractsProjectTenant.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsProjectTenant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsProjectTenant} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsProjectTenant} The populated <code>MozuAppDevContractsProjectTenant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsProjectTenant();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'Number');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('isGoldenTenant')) {
                obj['isGoldenTenant'] = ApiClient.convertToType(data['isGoldenTenant'], 'Boolean');
            }
            if (data.hasOwnProperty('isQaTenant')) {
                obj['isQaTenant'] = ApiClient.convertToType(data['isQaTenant'], 'Boolean');
            }
            if (data.hasOwnProperty('tenantName')) {
                obj['tenantName'] = ApiClient.convertToType(data['tenantName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsProjectTenant.prototype['id'] = undefined;

/**
 * @member {Number} projectId
 */
MozuAppDevContractsProjectTenant.prototype['projectId'] = undefined;

/**
 * @member {Number} tenantId
 */
MozuAppDevContractsProjectTenant.prototype['tenantId'] = undefined;

/**
 * @member {Boolean} isGoldenTenant
 */
MozuAppDevContractsProjectTenant.prototype['isGoldenTenant'] = undefined;

/**
 * @member {Boolean} isQaTenant
 */
MozuAppDevContractsProjectTenant.prototype['isQaTenant'] = undefined;

/**
 * @member {String} tenantName
 */
MozuAppDevContractsProjectTenant.prototype['tenantName'] = undefined;






export default MozuAppDevContractsProjectTenant;

