/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuTenantContractsDomain model module.
 * @module model/MozuTenantContractsDomain
 * @version v1
 */
class MozuTenantContractsDomain {
    /**
     * Constructs a new <code>MozuTenantContractsDomain</code>.
     * @alias module:model/MozuTenantContractsDomain
     */
    constructor() { 
        
        MozuTenantContractsDomain.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuTenantContractsDomain</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuTenantContractsDomain} obj Optional instance to populate.
     * @return {module:model/MozuTenantContractsDomain} The populated <code>MozuTenantContractsDomain</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuTenantContractsDomain();

            if (data.hasOwnProperty('domainName')) {
                obj['domainName'] = ApiClient.convertToType(data['domainName'], 'String');
            }
            if (data.hasOwnProperty('zone')) {
                obj['zone'] = ApiClient.convertToType(data['zone'], 'String');
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'Date');
            }
            if (data.hasOwnProperty('updateDate')) {
                obj['updateDate'] = ApiClient.convertToType(data['updateDate'], 'Date');
            }
            if (data.hasOwnProperty('isPrimary')) {
                obj['isPrimary'] = ApiClient.convertToType(data['isPrimary'], 'Boolean');
            }
            if (data.hasOwnProperty('isInfrastructureRecord')) {
                obj['isInfrastructureRecord'] = ApiClient.convertToType(data['isInfrastructureRecord'], 'Boolean');
            }
            if (data.hasOwnProperty('isSystemAssigned')) {
                obj['isSystemAssigned'] = ApiClient.convertToType(data['isSystemAssigned'], 'Boolean');
            }
            if (data.hasOwnProperty('isDomainManaged')) {
                obj['isDomainManaged'] = ApiClient.convertToType(data['isDomainManaged'], 'Boolean');
            }
            if (data.hasOwnProperty('ipAddress')) {
                obj['ipAddress'] = ApiClient.convertToType(data['ipAddress'], 'String');
            }
            if (data.hasOwnProperty('cName')) {
                obj['cName'] = ApiClient.convertToType(data['cName'], 'String');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('siteId')) {
                obj['siteId'] = ApiClient.convertToType(data['siteId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} domainName
 */
MozuTenantContractsDomain.prototype['domainName'] = undefined;

/**
 * @member {String} zone
 */
MozuTenantContractsDomain.prototype['zone'] = undefined;

/**
 * @member {Date} createDate
 */
MozuTenantContractsDomain.prototype['createDate'] = undefined;

/**
 * @member {Date} updateDate
 */
MozuTenantContractsDomain.prototype['updateDate'] = undefined;

/**
 * @member {Boolean} isPrimary
 */
MozuTenantContractsDomain.prototype['isPrimary'] = undefined;

/**
 * @member {Boolean} isInfrastructureRecord
 */
MozuTenantContractsDomain.prototype['isInfrastructureRecord'] = undefined;

/**
 * @member {Boolean} isSystemAssigned
 */
MozuTenantContractsDomain.prototype['isSystemAssigned'] = undefined;

/**
 * @member {Boolean} isDomainManaged
 */
MozuTenantContractsDomain.prototype['isDomainManaged'] = undefined;

/**
 * @member {String} ipAddress
 */
MozuTenantContractsDomain.prototype['ipAddress'] = undefined;

/**
 * @member {String} cName
 */
MozuTenantContractsDomain.prototype['cName'] = undefined;

/**
 * @member {Number} tenantId
 */
MozuTenantContractsDomain.prototype['tenantId'] = undefined;

/**
 * @member {Number} siteId
 */
MozuTenantContractsDomain.prototype['siteId'] = undefined;






export default MozuTenantContractsDomain;

