/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsLocalizedImage from './MozuAppDevContractsLocalizedImage';

/**
 * The MozuAppDevContractsLocalizedCategory model module.
 * @module model/MozuAppDevContractsLocalizedCategory
 * @version v1
 */
class MozuAppDevContractsLocalizedCategory {
    /**
     * Constructs a new <code>MozuAppDevContractsLocalizedCategory</code>.
     * @alias module:model/MozuAppDevContractsLocalizedCategory
     */
    constructor() { 
        
        MozuAppDevContractsLocalizedCategory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsLocalizedCategory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsLocalizedCategory} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsLocalizedCategory} The populated <code>MozuAppDevContractsLocalizedCategory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsLocalizedCategory();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('localeCode')) {
                obj['localeCode'] = ApiClient.convertToType(data['localeCode'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = MozuAppDevContractsLocalizedImage.constructFromObject(data['image']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsLocalizedCategory.prototype['id'] = undefined;

/**
 * @member {String} localeCode
 */
MozuAppDevContractsLocalizedCategory.prototype['localeCode'] = undefined;

/**
 * @member {String} name
 */
MozuAppDevContractsLocalizedCategory.prototype['name'] = undefined;

/**
 * @member {module:model/MozuAppDevContractsLocalizedImage} image
 */
MozuAppDevContractsLocalizedCategory.prototype['image'] = undefined;






export default MozuAppDevContractsLocalizedCategory;

