/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuCoreApiContractsProvisioningCreateCustomDomainRequest model module.
 * @module model/MozuCoreApiContractsProvisioningCreateCustomDomainRequest
 * @version v1
 */
class MozuCoreApiContractsProvisioningCreateCustomDomainRequest {
    /**
     * Constructs a new <code>MozuCoreApiContractsProvisioningCreateCustomDomainRequest</code>.
     * @alias module:model/MozuCoreApiContractsProvisioningCreateCustomDomainRequest
     */
    constructor() { 
        
        MozuCoreApiContractsProvisioningCreateCustomDomainRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreApiContractsProvisioningCreateCustomDomainRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreApiContractsProvisioningCreateCustomDomainRequest} obj Optional instance to populate.
     * @return {module:model/MozuCoreApiContractsProvisioningCreateCustomDomainRequest} The populated <code>MozuCoreApiContractsProvisioningCreateCustomDomainRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreApiContractsProvisioningCreateCustomDomainRequest();

            if (data.hasOwnProperty('domainName')) {
                obj['domainName'] = ApiClient.convertToType(data['domainName'], 'String');
            }
            if (data.hasOwnProperty('zone')) {
                obj['zone'] = ApiClient.convertToType(data['zone'], 'String');
            }
            if (data.hasOwnProperty('isPrimary')) {
                obj['isPrimary'] = ApiClient.convertToType(data['isPrimary'], 'Boolean');
            }
            if (data.hasOwnProperty('isDomainManaged')) {
                obj['isDomainManaged'] = ApiClient.convertToType(data['isDomainManaged'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} domainName
 */
MozuCoreApiContractsProvisioningCreateCustomDomainRequest.prototype['domainName'] = undefined;

/**
 * @member {String} zone
 */
MozuCoreApiContractsProvisioningCreateCustomDomainRequest.prototype['zone'] = undefined;

/**
 * @member {Boolean} isPrimary
 */
MozuCoreApiContractsProvisioningCreateCustomDomainRequest.prototype['isPrimary'] = undefined;

/**
 * @member {Boolean} isDomainManaged
 */
MozuCoreApiContractsProvisioningCreateCustomDomainRequest.prototype['isDomainManaged'] = undefined;






export default MozuCoreApiContractsProvisioningCreateCustomDomainRequest;

