/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuAppDevContractsAuthTicketRequest model module.
 * @module model/MozuAppDevContractsAuthTicketRequest
 * @version v1
 */
class MozuAppDevContractsAuthTicketRequest {
    /**
     * Constructs a new <code>MozuAppDevContractsAuthTicketRequest</code>.
     * @alias module:model/MozuAppDevContractsAuthTicketRequest
     */
    constructor() { 
        
        MozuAppDevContractsAuthTicketRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsAuthTicketRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsAuthTicketRequest} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsAuthTicketRequest} The populated <code>MozuAppDevContractsAuthTicketRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsAuthTicketRequest();

            if (data.hasOwnProperty('refreshToken')) {
                obj['refreshToken'] = ApiClient.convertToType(data['refreshToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} refreshToken
 */
MozuAppDevContractsAuthTicketRequest.prototype['refreshToken'] = undefined;






export default MozuAppDevContractsAuthTicketRequest;

