/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuCoreMessagingContractsMessagePublishingContext from './MozuCoreMessagingContractsMessagePublishingContext';

/**
 * The MozuCoreMessagingContractsNotificationEmailNotification model module.
 * @module model/MozuCoreMessagingContractsNotificationEmailNotification
 * @version v1
 */
class MozuCoreMessagingContractsNotificationEmailNotification {
    /**
     * Constructs a new <code>MozuCoreMessagingContractsNotificationEmailNotification</code>.
     * @alias module:model/MozuCoreMessagingContractsNotificationEmailNotification
     */
    constructor() { 
        
        MozuCoreMessagingContractsNotificationEmailNotification.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreMessagingContractsNotificationEmailNotification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreMessagingContractsNotificationEmailNotification} obj Optional instance to populate.
     * @return {module:model/MozuCoreMessagingContractsNotificationEmailNotification} The populated <code>MozuCoreMessagingContractsNotificationEmailNotification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreMessagingContractsNotificationEmailNotification();

            if (data.hasOwnProperty('messageId')) {
                obj['messageId'] = ApiClient.convertToType(data['messageId'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
            if (data.hasOwnProperty('payloadVersion')) {
                obj['payloadVersion'] = ApiClient.convertToType(data['payloadVersion'], 'String');
            }
            if (data.hasOwnProperty('topic')) {
                obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
            }
            if (data.hasOwnProperty('messagePublishingContext')) {
                obj['messagePublishingContext'] = MozuCoreMessagingContractsMessagePublishingContext.constructFromObject(data['messagePublishingContext']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} messageId
 */
MozuCoreMessagingContractsNotificationEmailNotification.prototype['messageId'] = undefined;

/**
 * @member {String} payload
 */
MozuCoreMessagingContractsNotificationEmailNotification.prototype['payload'] = undefined;

/**
 * @member {String} payloadVersion
 */
MozuCoreMessagingContractsNotificationEmailNotification.prototype['payloadVersion'] = undefined;

/**
 * @member {String} topic
 */
MozuCoreMessagingContractsNotificationEmailNotification.prototype['topic'] = undefined;

/**
 * @member {module:model/MozuCoreMessagingContractsMessagePublishingContext} messagePublishingContext
 */
MozuCoreMessagingContractsNotificationEmailNotification.prototype['messagePublishingContext'] = undefined;






export default MozuCoreMessagingContractsNotificationEmailNotification;

