/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsDeveloper from './MozuAppDevContractsDeveloper';
import MozuAppDevContractsDeveloperAccountContact from './MozuAppDevContractsDeveloperAccountContact';
import MozuAppDevContractsSocialContact from './MozuAppDevContractsSocialContact';

/**
 * The MozuAppDevContractsDeveloperAccount model module.
 * @module model/MozuAppDevContractsDeveloperAccount
 * @version v1
 */
class MozuAppDevContractsDeveloperAccount {
    /**
     * Constructs a new <code>MozuAppDevContractsDeveloperAccount</code>.
     * @alias module:model/MozuAppDevContractsDeveloperAccount
     */
    constructor() { 
        
        MozuAppDevContractsDeveloperAccount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsDeveloperAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsDeveloperAccount} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsDeveloperAccount} The populated <code>MozuAppDevContractsDeveloperAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsDeveloperAccount();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('namespace')) {
                obj['namespace'] = ApiClient.convertToType(data['namespace'], 'String');
            }
            if (data.hasOwnProperty('ownerUserId')) {
                obj['ownerUserId'] = ApiClient.convertToType(data['ownerUserId'], 'String');
            }
            if (data.hasOwnProperty('developerOwner')) {
                obj['developerOwner'] = MozuAppDevContractsDeveloper.constructFromObject(data['developerOwner']);
            }
            if (data.hasOwnProperty('contacts')) {
                obj['contacts'] = ApiClient.convertToType(data['contacts'], [MozuAppDevContractsDeveloperAccountContact]);
            }
            if (data.hasOwnProperty('socialContacts')) {
                obj['socialContacts'] = ApiClient.convertToType(data['socialContacts'], [MozuAppDevContractsSocialContact]);
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('mozuInstanceId')) {
                obj['mozuInstanceId'] = ApiClient.convertToType(data['mozuInstanceId'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('supportsCustomExtensions')) {
                obj['supportsCustomExtensions'] = ApiClient.convertToType(data['supportsCustomExtensions'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsDeveloperAccount.prototype['id'] = undefined;

/**
 * @member {String} type
 */
MozuAppDevContractsDeveloperAccount.prototype['type'] = undefined;

/**
 * @member {String} name
 */
MozuAppDevContractsDeveloperAccount.prototype['name'] = undefined;

/**
 * @member {String} namespace
 */
MozuAppDevContractsDeveloperAccount.prototype['namespace'] = undefined;

/**
 * @member {String} ownerUserId
 */
MozuAppDevContractsDeveloperAccount.prototype['ownerUserId'] = undefined;

/**
 * @member {module:model/MozuAppDevContractsDeveloper} developerOwner
 */
MozuAppDevContractsDeveloperAccount.prototype['developerOwner'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsDeveloperAccountContact>} contacts
 */
MozuAppDevContractsDeveloperAccount.prototype['contacts'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsSocialContact>} socialContacts
 */
MozuAppDevContractsDeveloperAccount.prototype['socialContacts'] = undefined;

/**
 * @member {Number} tenantId
 */
MozuAppDevContractsDeveloperAccount.prototype['tenantId'] = undefined;

/**
 * @member {String} mozuInstanceId
 */
MozuAppDevContractsDeveloperAccount.prototype['mozuInstanceId'] = undefined;

/**
 * @member {Boolean} isActive
 */
MozuAppDevContractsDeveloperAccount.prototype['isActive'] = undefined;

/**
 * @member {Boolean} supportsCustomExtensions
 */
MozuAppDevContractsDeveloperAccount.prototype['supportsCustomExtensions'] = undefined;






export default MozuAppDevContractsDeveloperAccount;

