/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuCoreApiContractsAddress model module.
 * @module model/MozuCoreApiContractsAddress
 * @version v1
 */
class MozuCoreApiContractsAddress {
    /**
     * Constructs a new <code>MozuCoreApiContractsAddress</code>.
     * @alias module:model/MozuCoreApiContractsAddress
     */
    constructor() { 
        
        MozuCoreApiContractsAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreApiContractsAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreApiContractsAddress} obj Optional instance to populate.
     * @return {module:model/MozuCoreApiContractsAddress} The populated <code>MozuCoreApiContractsAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreApiContractsAddress();

            if (data.hasOwnProperty('address1')) {
                obj['address1'] = ApiClient.convertToType(data['address1'], 'String');
            }
            if (data.hasOwnProperty('address2')) {
                obj['address2'] = ApiClient.convertToType(data['address2'], 'String');
            }
            if (data.hasOwnProperty('address3')) {
                obj['address3'] = ApiClient.convertToType(data['address3'], 'String');
            }
            if (data.hasOwnProperty('address4')) {
                obj['address4'] = ApiClient.convertToType(data['address4'], 'String');
            }
            if (data.hasOwnProperty('cityOrTown')) {
                obj['cityOrTown'] = ApiClient.convertToType(data['cityOrTown'], 'String');
            }
            if (data.hasOwnProperty('stateOrProvince')) {
                obj['stateOrProvince'] = ApiClient.convertToType(data['stateOrProvince'], 'String');
            }
            if (data.hasOwnProperty('postalOrZipCode')) {
                obj['postalOrZipCode'] = ApiClient.convertToType(data['postalOrZipCode'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('addressType')) {
                obj['addressType'] = ApiClient.convertToType(data['addressType'], 'String');
            }
            if (data.hasOwnProperty('isValidated')) {
                obj['isValidated'] = ApiClient.convertToType(data['isValidated'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} address1
 */
MozuCoreApiContractsAddress.prototype['address1'] = undefined;

/**
 * @member {String} address2
 */
MozuCoreApiContractsAddress.prototype['address2'] = undefined;

/**
 * @member {String} address3
 */
MozuCoreApiContractsAddress.prototype['address3'] = undefined;

/**
 * @member {String} address4
 */
MozuCoreApiContractsAddress.prototype['address4'] = undefined;

/**
 * @member {String} cityOrTown
 */
MozuCoreApiContractsAddress.prototype['cityOrTown'] = undefined;

/**
 * @member {String} stateOrProvince
 */
MozuCoreApiContractsAddress.prototype['stateOrProvince'] = undefined;

/**
 * @member {String} postalOrZipCode
 */
MozuCoreApiContractsAddress.prototype['postalOrZipCode'] = undefined;

/**
 * @member {String} countryCode
 */
MozuCoreApiContractsAddress.prototype['countryCode'] = undefined;

/**
 * @member {String} addressType
 */
MozuCoreApiContractsAddress.prototype['addressType'] = undefined;

/**
 * @member {Boolean} isValidated
 */
MozuCoreApiContractsAddress.prototype['isValidated'] = undefined;






export default MozuCoreApiContractsAddress;

