/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsDeveloperContact from './MozuAppDevContractsDeveloperContact';

/**
 * The MozuAppDevContractsDeveloper model module.
 * @module model/MozuAppDevContractsDeveloper
 * @version v1
 */
class MozuAppDevContractsDeveloper {
    /**
     * Constructs a new <code>MozuAppDevContractsDeveloper</code>.
     * @alias module:model/MozuAppDevContractsDeveloper
     */
    constructor() { 
        
        MozuAppDevContractsDeveloper.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsDeveloper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsDeveloper} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsDeveloper} The populated <code>MozuAppDevContractsDeveloper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsDeveloper();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('contacts')) {
                obj['contacts'] = ApiClient.convertToType(data['contacts'], [MozuAppDevContractsDeveloperContact]);
            }
            if (data.hasOwnProperty('doesAcceptMarketing')) {
                obj['doesAcceptMarketing'] = ApiClient.convertToType(data['doesAcceptMarketing'], 'Boolean');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MozuAppDevContractsDeveloper.prototype['id'] = undefined;

/**
 * @member {String} userId
 */
MozuAppDevContractsDeveloper.prototype['userId'] = undefined;

/**
 * @member {String} type
 */
MozuAppDevContractsDeveloper.prototype['type'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsDeveloperContact>} contacts
 */
MozuAppDevContractsDeveloper.prototype['contacts'] = undefined;

/**
 * @member {Boolean} doesAcceptMarketing
 */
MozuAppDevContractsDeveloper.prototype['doesAcceptMarketing'] = undefined;

/**
 * @member {Boolean} isActive
 */
MozuAppDevContractsDeveloper.prototype['isActive'] = undefined;






export default MozuAppDevContractsDeveloper;

