/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuCoreApiContractsProvisioningCreateMasterCatalogRequest from './MozuCoreApiContractsProvisioningCreateMasterCatalogRequest';

/**
 * The MozuCoreApiContractsProvisioningCreateTenantRequest model module.
 * @module model/MozuCoreApiContractsProvisioningCreateTenantRequest
 * @version v1
 */
class MozuCoreApiContractsProvisioningCreateTenantRequest {
    /**
     * Constructs a new <code>MozuCoreApiContractsProvisioningCreateTenantRequest</code>.
     * @alias module:model/MozuCoreApiContractsProvisioningCreateTenantRequest
     */
    constructor() { 
        
        MozuCoreApiContractsProvisioningCreateTenantRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreApiContractsProvisioningCreateTenantRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreApiContractsProvisioningCreateTenantRequest} obj Optional instance to populate.
     * @return {module:model/MozuCoreApiContractsProvisioningCreateTenantRequest} The populated <code>MozuCoreApiContractsProvisioningCreateTenantRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreApiContractsProvisioningCreateTenantRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('masterCatalogs')) {
                obj['masterCatalogs'] = ApiClient.convertToType(data['masterCatalogs'], [MozuCoreApiContractsProvisioningCreateMasterCatalogRequest]);
            }
            if (data.hasOwnProperty('scaleUnitId')) {
                obj['scaleUnitId'] = ApiClient.convertToType(data['scaleUnitId'], 'String');
            }
            if (data.hasOwnProperty('isDevTenant')) {
                obj['isDevTenant'] = ApiClient.convertToType(data['isDevTenant'], 'Boolean');
            }
            if (data.hasOwnProperty('devAccountId')) {
                obj['devAccountId'] = ApiClient.convertToType(data['devAccountId'], 'Number');
            }
            if (data.hasOwnProperty('additionalData')) {
                obj['additionalData'] = ApiClient.convertToType(data['additionalData'], Object);
            }
            if (data.hasOwnProperty('omsMerchantId')) {
                obj['omsMerchantId'] = ApiClient.convertToType(data['omsMerchantId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} tenantId
 */
MozuCoreApiContractsProvisioningCreateTenantRequest.prototype['tenantId'] = undefined;

/**
 * @member {String} name
 */
MozuCoreApiContractsProvisioningCreateTenantRequest.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/MozuCoreApiContractsProvisioningCreateMasterCatalogRequest>} masterCatalogs
 */
MozuCoreApiContractsProvisioningCreateTenantRequest.prototype['masterCatalogs'] = undefined;

/**
 * @member {String} scaleUnitId
 */
MozuCoreApiContractsProvisioningCreateTenantRequest.prototype['scaleUnitId'] = undefined;

/**
 * @member {Boolean} isDevTenant
 */
MozuCoreApiContractsProvisioningCreateTenantRequest.prototype['isDevTenant'] = undefined;

/**
 * @member {Number} devAccountId
 */
MozuCoreApiContractsProvisioningCreateTenantRequest.prototype['devAccountId'] = undefined;

/**
 * @member {Object} additionalData
 */
MozuCoreApiContractsProvisioningCreateTenantRequest.prototype['additionalData'] = undefined;

/**
 * @member {Number} omsMerchantId
 */
MozuCoreApiContractsProvisioningCreateTenantRequest.prototype['omsMerchantId'] = undefined;






export default MozuCoreApiContractsProvisioningCreateTenantRequest;

