/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MozuAppDevContractsRoleInfo from './MozuAppDevContractsRoleInfo';

/**
 * The MozuAppDevContractsDeveloperAccountUser model module.
 * @module model/MozuAppDevContractsDeveloperAccountUser
 * @version v1
 */
class MozuAppDevContractsDeveloperAccountUser {
    /**
     * Constructs a new <code>MozuAppDevContractsDeveloperAccountUser</code>.
     * @alias module:model/MozuAppDevContractsDeveloperAccountUser
     */
    constructor() { 
        
        MozuAppDevContractsDeveloperAccountUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuAppDevContractsDeveloperAccountUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuAppDevContractsDeveloperAccountUser} obj Optional instance to populate.
     * @return {module:model/MozuAppDevContractsDeveloperAccountUser} The populated <code>MozuAppDevContractsDeveloperAccountUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuAppDevContractsDeveloperAccountUser();

            if (data.hasOwnProperty('developerId')) {
                obj['developerId'] = ApiClient.convertToType(data['developerId'], 'Number');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('workContactId')) {
                obj['workContactId'] = ApiClient.convertToType(data['workContactId'], 'Number');
            }
            if (data.hasOwnProperty('workAddress1')) {
                obj['workAddress1'] = ApiClient.convertToType(data['workAddress1'], 'String');
            }
            if (data.hasOwnProperty('workAddress2')) {
                obj['workAddress2'] = ApiClient.convertToType(data['workAddress2'], 'String');
            }
            if (data.hasOwnProperty('workAddress3')) {
                obj['workAddress3'] = ApiClient.convertToType(data['workAddress3'], 'String');
            }
            if (data.hasOwnProperty('workAddress4')) {
                obj['workAddress4'] = ApiClient.convertToType(data['workAddress4'], 'String');
            }
            if (data.hasOwnProperty('workCity')) {
                obj['workCity'] = ApiClient.convertToType(data['workCity'], 'String');
            }
            if (data.hasOwnProperty('workState')) {
                obj['workState'] = ApiClient.convertToType(data['workState'], 'String');
            }
            if (data.hasOwnProperty('workZip')) {
                obj['workZip'] = ApiClient.convertToType(data['workZip'], 'String');
            }
            if (data.hasOwnProperty('workCountry')) {
                obj['workCountry'] = ApiClient.convertToType(data['workCountry'], 'String');
            }
            if (data.hasOwnProperty('workPhone')) {
                obj['workPhone'] = ApiClient.convertToType(data['workPhone'], 'String');
            }
            if (data.hasOwnProperty('personalContactId')) {
                obj['personalContactId'] = ApiClient.convertToType(data['personalContactId'], 'Number');
            }
            if (data.hasOwnProperty('personalAddress1')) {
                obj['personalAddress1'] = ApiClient.convertToType(data['personalAddress1'], 'String');
            }
            if (data.hasOwnProperty('personalAddress2')) {
                obj['personalAddress2'] = ApiClient.convertToType(data['personalAddress2'], 'String');
            }
            if (data.hasOwnProperty('personalAddress3')) {
                obj['personalAddress3'] = ApiClient.convertToType(data['personalAddress3'], 'String');
            }
            if (data.hasOwnProperty('personalAddress4')) {
                obj['personalAddress4'] = ApiClient.convertToType(data['personalAddress4'], 'String');
            }
            if (data.hasOwnProperty('personalCity')) {
                obj['personalCity'] = ApiClient.convertToType(data['personalCity'], 'String');
            }
            if (data.hasOwnProperty('personalState')) {
                obj['personalState'] = ApiClient.convertToType(data['personalState'], 'String');
            }
            if (data.hasOwnProperty('personalZip')) {
                obj['personalZip'] = ApiClient.convertToType(data['personalZip'], 'String');
            }
            if (data.hasOwnProperty('personalCountry')) {
                obj['personalCountry'] = ApiClient.convertToType(data['personalCountry'], 'String');
            }
            if (data.hasOwnProperty('personalPhone')) {
                obj['personalPhone'] = ApiClient.convertToType(data['personalPhone'], 'String');
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], [MozuAppDevContractsRoleInfo]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} developerId
 */
MozuAppDevContractsDeveloperAccountUser.prototype['developerId'] = undefined;

/**
 * @member {String} userId
 */
MozuAppDevContractsDeveloperAccountUser.prototype['userId'] = undefined;

/**
 * @member {String} firstName
 */
MozuAppDevContractsDeveloperAccountUser.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
MozuAppDevContractsDeveloperAccountUser.prototype['lastName'] = undefined;

/**
 * @member {String} emailAddress
 */
MozuAppDevContractsDeveloperAccountUser.prototype['emailAddress'] = undefined;

/**
 * @member {String} type
 */
MozuAppDevContractsDeveloperAccountUser.prototype['type'] = undefined;

/**
 * @member {Number} workContactId
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workContactId'] = undefined;

/**
 * @member {String} workAddress1
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workAddress1'] = undefined;

/**
 * @member {String} workAddress2
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workAddress2'] = undefined;

/**
 * @member {String} workAddress3
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workAddress3'] = undefined;

/**
 * @member {String} workAddress4
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workAddress4'] = undefined;

/**
 * @member {String} workCity
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workCity'] = undefined;

/**
 * @member {String} workState
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workState'] = undefined;

/**
 * @member {String} workZip
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workZip'] = undefined;

/**
 * @member {String} workCountry
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workCountry'] = undefined;

/**
 * @member {String} workPhone
 */
MozuAppDevContractsDeveloperAccountUser.prototype['workPhone'] = undefined;

/**
 * @member {Number} personalContactId
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalContactId'] = undefined;

/**
 * @member {String} personalAddress1
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalAddress1'] = undefined;

/**
 * @member {String} personalAddress2
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalAddress2'] = undefined;

/**
 * @member {String} personalAddress3
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalAddress3'] = undefined;

/**
 * @member {String} personalAddress4
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalAddress4'] = undefined;

/**
 * @member {String} personalCity
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalCity'] = undefined;

/**
 * @member {String} personalState
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalState'] = undefined;

/**
 * @member {String} personalZip
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalZip'] = undefined;

/**
 * @member {String} personalCountry
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalCountry'] = undefined;

/**
 * @member {String} personalPhone
 */
MozuAppDevContractsDeveloperAccountUser.prototype['personalPhone'] = undefined;

/**
 * @member {Array.<module:model/MozuAppDevContractsRoleInfo>} roles
 */
MozuAppDevContractsDeveloperAccountUser.prototype['roles'] = undefined;






export default MozuAppDevContractsDeveloperAccountUser;

