/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MozuCoreApiContractsUserSystemData model module.
 * @module model/MozuCoreApiContractsUserSystemData
 * @version v1
 */
class MozuCoreApiContractsUserSystemData {
    /**
     * Constructs a new <code>MozuCoreApiContractsUserSystemData</code>.
     * @alias module:model/MozuCoreApiContractsUserSystemData
     */
    constructor() { 
        
        MozuCoreApiContractsUserSystemData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MozuCoreApiContractsUserSystemData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MozuCoreApiContractsUserSystemData} obj Optional instance to populate.
     * @return {module:model/MozuCoreApiContractsUserSystemData} The populated <code>MozuCoreApiContractsUserSystemData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MozuCoreApiContractsUserSystemData();

            if (data.hasOwnProperty('isPasswordChangeRequired')) {
                obj['isPasswordChangeRequired'] = ApiClient.convertToType(data['isPasswordChangeRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('lastPasswordChangeOn')) {
                obj['lastPasswordChangeOn'] = ApiClient.convertToType(data['lastPasswordChangeOn'], 'Date');
            }
            if (data.hasOwnProperty('isLocked')) {
                obj['isLocked'] = ApiClient.convertToType(data['isLocked'], 'Boolean');
            }
            if (data.hasOwnProperty('lastLockedOn')) {
                obj['lastLockedOn'] = ApiClient.convertToType(data['lastLockedOn'], 'Date');
            }
            if (data.hasOwnProperty('failedLoginAttemptCount')) {
                obj['failedLoginAttemptCount'] = ApiClient.convertToType(data['failedLoginAttemptCount'], 'Number');
            }
            if (data.hasOwnProperty('remainingLoginAttempts')) {
                obj['remainingLoginAttempts'] = ApiClient.convertToType(data['remainingLoginAttempts'], 'Number');
            }
            if (data.hasOwnProperty('firstFailedLoginAttemptOn')) {
                obj['firstFailedLoginAttemptOn'] = ApiClient.convertToType(data['firstFailedLoginAttemptOn'], 'Date');
            }
            if (data.hasOwnProperty('lastLoginOn')) {
                obj['lastLoginOn'] = ApiClient.convertToType(data['lastLoginOn'], 'Date');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('updatedOn')) {
                obj['updatedOn'] = ApiClient.convertToType(data['updatedOn'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} isPasswordChangeRequired
 */
MozuCoreApiContractsUserSystemData.prototype['isPasswordChangeRequired'] = undefined;

/**
 * @member {Date} lastPasswordChangeOn
 */
MozuCoreApiContractsUserSystemData.prototype['lastPasswordChangeOn'] = undefined;

/**
 * @member {Boolean} isLocked
 */
MozuCoreApiContractsUserSystemData.prototype['isLocked'] = undefined;

/**
 * @member {Date} lastLockedOn
 */
MozuCoreApiContractsUserSystemData.prototype['lastLockedOn'] = undefined;

/**
 * @member {Number} failedLoginAttemptCount
 */
MozuCoreApiContractsUserSystemData.prototype['failedLoginAttemptCount'] = undefined;

/**
 * @member {Number} remainingLoginAttempts
 */
MozuCoreApiContractsUserSystemData.prototype['remainingLoginAttempts'] = undefined;

/**
 * @member {Date} firstFailedLoginAttemptOn
 */
MozuCoreApiContractsUserSystemData.prototype['firstFailedLoginAttemptOn'] = undefined;

/**
 * @member {Date} lastLoginOn
 */
MozuCoreApiContractsUserSystemData.prototype['lastLoginOn'] = undefined;

/**
 * @member {Date} createdOn
 */
MozuCoreApiContractsUserSystemData.prototype['createdOn'] = undefined;

/**
 * @member {Date} updatedOn
 */
MozuCoreApiContractsUserSystemData.prototype['updatedOn'] = undefined;






export default MozuCoreApiContractsUserSystemData;

