/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuCoreMessagingContractsMessagePublishingContext', function() {
    it('should create an instance of MozuCoreMessagingContractsMessagePublishingContext', function() {
      // uncomment below and update the code to test MozuCoreMessagingContractsMessagePublishingContext
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be.a(KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext);
    });

    it('should have the property siteId (base name: "siteId")', function() {
      // uncomment below and update the code to test the property siteId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property catalogId (base name: "catalogId")', function() {
      // uncomment below and update the code to test the property catalogId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property masterCatalogId (base name: "masterCatalogId")', function() {
      // uncomment below and update the code to test the property masterCatalogId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property localeCode (base name: "localeCode")', function() {
      // uncomment below and update the code to test the property localeCode
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property currencyCode (base name: "currencyCode")', function() {
      // uncomment below and update the code to test the property currencyCode
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customerId")', function() {
      // uncomment below and update the code to test the property customerId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property visitId (base name: "visitId")', function() {
      // uncomment below and update the code to test the property visitId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property initiatingAppId (base name: "initiatingAppId")', function() {
      // uncomment below and update the code to test the property initiatingAppId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property correlationId (base name: "correlationId")', function() {
      // uncomment below and update the code to test the property correlationId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property isTest (base name: "isTest")', function() {
      // uncomment below and update the code to test the property isTest
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property createDate (base name: "createDate")', function() {
      // uncomment below and update the code to test the property createDate
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property createBy (base name: "createBy")', function() {
      // uncomment below and update the code to test the property createBy
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property dataViewMode (base name: "dataViewMode")', function() {
      // uncomment below and update the code to test the property dataViewMode
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

    it('should have the property mozuInstanceId (base name: "mozuInstanceId")', function() {
      // uncomment below and update the code to test the property mozuInstanceId
      //var instane = new KiboAppDevService.MozuCoreMessagingContractsMessagePublishingContext();
      //expect(instance).to.be();
    });

  });

}));
