/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuCoreApiContractsUserSystemData', function() {
    it('should create an instance of MozuCoreApiContractsUserSystemData', function() {
      // uncomment below and update the code to test MozuCoreApiContractsUserSystemData
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be.a(KiboAppDevService.MozuCoreApiContractsUserSystemData);
    });

    it('should have the property isPasswordChangeRequired (base name: "isPasswordChangeRequired")', function() {
      // uncomment below and update the code to test the property isPasswordChangeRequired
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property lastPasswordChangeOn (base name: "lastPasswordChangeOn")', function() {
      // uncomment below and update the code to test the property lastPasswordChangeOn
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property isLocked (base name: "isLocked")', function() {
      // uncomment below and update the code to test the property isLocked
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property lastLockedOn (base name: "lastLockedOn")', function() {
      // uncomment below and update the code to test the property lastLockedOn
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property failedLoginAttemptCount (base name: "failedLoginAttemptCount")', function() {
      // uncomment below and update the code to test the property failedLoginAttemptCount
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property remainingLoginAttempts (base name: "remainingLoginAttempts")', function() {
      // uncomment below and update the code to test the property remainingLoginAttempts
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property firstFailedLoginAttemptOn (base name: "firstFailedLoginAttemptOn")', function() {
      // uncomment below and update the code to test the property firstFailedLoginAttemptOn
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property lastLoginOn (base name: "lastLoginOn")', function() {
      // uncomment below and update the code to test the property lastLoginOn
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

    it('should have the property updatedOn (base name: "updatedOn")', function() {
      // uncomment below and update the code to test the property updatedOn
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserSystemData();
      //expect(instance).to.be();
    });

  });

}));
