/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuAppDevContractsTenant();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuAppDevContractsTenant', function() {
    it('should create an instance of MozuAppDevContractsTenant', function() {
      // uncomment below and update the code to test MozuAppDevContractsTenant
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be.a(KiboAppDevService.MozuAppDevContractsTenant);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property sites (base name: "sites")', function() {
      // uncomment below and update the code to test the property sites
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property masterCatalogs (base name: "masterCatalogs")', function() {
      // uncomment below and update the code to test the property masterCatalogs
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property isDevTenant (base name: "isDevTenant")', function() {
      // uncomment below and update the code to test the property isDevTenant
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property themeCount (base name: "themeCount")', function() {
      // uncomment below and update the code to test the property themeCount
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property appCount (base name: "appCount")', function() {
      // uncomment below and update the code to test the property appCount
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property correlationId (base name: "correlationId")', function() {
      // uncomment below and update the code to test the property correlationId
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property developerAccountId (base name: "developerAccountId")', function() {
      // uncomment below and update the code to test the property developerAccountId
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property enableBetaAdmin (base name: "enableBetaAdmin")', function() {
      // uncomment below and update the code to test the property enableBetaAdmin
      //var instane = new KiboAppDevService.MozuAppDevContractsTenant();
      //expect(instance).to.be();
    });

  });

}));
