/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuAppDevContractsDevAccountMember', function() {
    it('should create an instance of MozuAppDevContractsDevAccountMember', function() {
      // uncomment below and update the code to test MozuAppDevContractsDevAccountMember
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be.a(KiboAppDevService.MozuAppDevContractsDevAccountMember);
    });

    it('should have the property emailAddress (base name: "emailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be();
    });

    it('should have the property dateLastSent (base name: "dateLastSent")', function() {
      // uncomment below and update the code to test the property dateLastSent
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be();
    });

    it('should have the property invitationState (base name: "invitationState")', function() {
      // uncomment below and update the code to test the property invitationState
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be();
    });

    it('should have the property invitationId (base name: "invitationId")', function() {
      // uncomment below and update the code to test the property invitationId
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be();
    });

    it('should have the property roleId (base name: "roleId")', function() {
      // uncomment below and update the code to test the property roleId
      //var instane = new KiboAppDevService.MozuAppDevContractsDevAccountMember();
      //expect(instance).to.be();
    });

  });

}));
