/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuProvisioningContractsCatalogProvisionRequest', function() {
    it('should create an instance of MozuProvisioningContractsCatalogProvisionRequest', function() {
      // uncomment below and update the code to test MozuProvisioningContractsCatalogProvisionRequest
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be.a(KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest);
    });

    it('should have the property isOverride (base name: "isOverride")', function() {
      // uncomment below and update the code to test the property isOverride
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be();
    });

    it('should have the property isRetry (base name: "isRetry")', function() {
      // uncomment below and update the code to test the property isRetry
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be();
    });

    it('should have the property masterCatalogId (base name: "masterCatalogId")', function() {
      // uncomment below and update the code to test the property masterCatalogId
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be();
    });

    it('should have the property catalogId (base name: "catalogId")', function() {
      // uncomment below and update the code to test the property catalogId
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be();
    });

    it('should have the property defaultLocaleCode (base name: "defaultLocaleCode")', function() {
      // uncomment below and update the code to test the property defaultLocaleCode
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be();
    });

    it('should have the property defaultCurrencyCode (base name: "defaultCurrencyCode")', function() {
      // uncomment below and update the code to test the property defaultCurrencyCode
      //var instane = new KiboAppDevService.MozuProvisioningContractsCatalogProvisionRequest();
      //expect(instance).to.be();
    });

  });

}));
