/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuAppDevContractsCapabilityTypeContract', function() {
    it('should create an instance of MozuAppDevContractsCapabilityTypeContract', function() {
      // uncomment below and update the code to test MozuAppDevContractsCapabilityTypeContract
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be.a(KiboAppDevService.MozuAppDevContractsCapabilityTypeContract);
    });

    it('should have the property capabilityTypeContractId (base name: "capabilityTypeContractId")', function() {
      // uncomment below and update the code to test the property capabilityTypeContractId
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be();
    });

    it('should have the property contractName (base name: "contractName")', function() {
      // uncomment below and update the code to test the property contractName
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be();
    });

    it('should have the property contractDescription (base name: "contractDescription")', function() {
      // uncomment below and update the code to test the property contractDescription
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be();
    });

    it('should have the property contractDefinitionUrl (base name: "contractDefinitionUrl")', function() {
      // uncomment below and update the code to test the property contractDefinitionUrl
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be();
    });

    it('should have the property auditInfo (base name: "auditInfo")', function() {
      // uncomment below and update the code to test the property auditInfo
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be();
    });

    it('should have the property capabilityTypeId (base name: "capabilityTypeId")', function() {
      // uncomment below and update the code to test the property capabilityTypeId
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be();
    });

    it('should have the property isRequired (base name: "isRequired")', function() {
      // uncomment below and update the code to test the property isRequired
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be();
    });

    it('should have the property verb (base name: "verb")', function() {
      // uncomment below and update the code to test the property verb
      //var instane = new KiboAppDevService.MozuAppDevContractsCapabilityTypeContract();
      //expect(instance).to.be();
    });

  });

}));
