/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuAppDevContractsApplicationTransaction', function() {
    it('should create an instance of MozuAppDevContractsApplicationTransaction', function() {
      // uncomment below and update the code to test MozuAppDevContractsApplicationTransaction
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be.a(KiboAppDevService.MozuAppDevContractsApplicationTransaction);
    });

    it('should have the property applicationTransactionId (base name: "applicationTransactionId")', function() {
      // uncomment below and update the code to test the property applicationTransactionId
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property applicationId (base name: "applicationId")', function() {
      // uncomment below and update the code to test the property applicationId
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property applicationEntitlementId (base name: "applicationEntitlementId")', function() {
      // uncomment below and update the code to test the property applicationEntitlementId
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property siteId (base name: "siteId")', function() {
      // uncomment below and update the code to test the property siteId
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property localeCode (base name: "localeCode")', function() {
      // uncomment below and update the code to test the property localeCode
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property isoCurrencyCode (base name: "isoCurrencyCode")', function() {
      // uncomment below and update the code to test the property isoCurrencyCode
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionDate (base name: "transactionDate")', function() {
      // uncomment below and update the code to test the property transactionDate
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionPrice (base name: "transactionPrice")', function() {
      // uncomment below and update the code to test the property transactionPrice
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionTax (base name: "transactionTax")', function() {
      // uncomment below and update the code to test the property transactionTax
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionTotal (base name: "transactionTotal")', function() {
      // uncomment below and update the code to test the property transactionTotal
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

    it('should have the property orderNumber (base name: "orderNumber")', function() {
      // uncomment below and update the code to test the property orderNumber
      //var instane = new KiboAppDevService.MozuAppDevContractsApplicationTransaction();
      //expect(instance).to.be();
    });

  });

}));
