/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuAppDevContractsAppStoreLocalizedProfile', function() {
    it('should create an instance of MozuAppDevContractsAppStoreLocalizedProfile', function() {
      // uncomment below and update the code to test MozuAppDevContractsAppStoreLocalizedProfile
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be.a(KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile);
    });

    it('should have the property localeCode (base name: "localeCode")', function() {
      // uncomment below and update the code to test the property localeCode
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property appProductCode (base name: "appProductCode")', function() {
      // uncomment below and update the code to test the property appProductCode
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property appStoreName (base name: "appStoreName")', function() {
      // uncomment below and update the code to test the property appStoreName
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property shortDescription (base name: "shortDescription")', function() {
      // uncomment below and update the code to test the property shortDescription
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property longDescription (base name: "longDescription")', function() {
      // uncomment below and update the code to test the property longDescription
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property releaseNotes (base name: "releaseNotes")', function() {
      // uncomment below and update the code to test the property releaseNotes
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property support (base name: "support")', function() {
      // uncomment below and update the code to test the property support
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property prerequisites (base name: "prerequisites")', function() {
      // uncomment below and update the code to test the property prerequisites
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property publishDate (base name: "publishDate")', function() {
      // uncomment below and update the code to test the property publishDate
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property inactiveDate (base name: "inactiveDate")', function() {
      // uncomment below and update the code to test the property inactiveDate
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

    it('should have the property auditInfo (base name: "auditInfo")', function() {
      // uncomment below and update the code to test the property auditInfo
      //var instane = new KiboAppDevService.MozuAppDevContractsAppStoreLocalizedProfile();
      //expect(instance).to.be();
    });

  });

}));
