/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuAdminUserContractsInvitation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuAdminUserContractsInvitation', function() {
    it('should create an instance of MozuAdminUserContractsInvitation', function() {
      // uncomment below and update the code to test MozuAdminUserContractsInvitation
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be.a(KiboAppDevService.MozuAdminUserContractsInvitation);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property userScopeType (base name: "userScopeType")', function() {
      // uncomment below and update the code to test the property userScopeType
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property userScopeId (base name: "userScopeId")', function() {
      // uncomment below and update the code to test the property userScopeId
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property scopeName (base name: "scopeName")', function() {
      // uncomment below and update the code to test the property scopeName
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property roleId (base name: "roleId")', function() {
      // uncomment below and update the code to test the property roleId
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property emailAddress (base name: "emailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property invitationRoles (base name: "invitationRoles")', function() {
      // uncomment below and update the code to test the property invitationRoles
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property dateLastSent (base name: "dateLastSent")', function() {
      // uncomment below and update the code to test the property dateLastSent
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

    it('should have the property auditInfo (base name: "auditInfo")', function() {
      // uncomment below and update the code to test the property auditInfo
      //var instane = new KiboAppDevService.MozuAdminUserContractsInvitation();
      //expect(instance).to.be();
    });

  });

}));
