/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuTenantContractsTenant();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuTenantContractsTenant', function() {
    it('should create an instance of MozuTenantContractsTenant', function() {
      // uncomment below and update the code to test MozuTenantContractsTenant
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be.a(KiboAppDevService.MozuTenantContractsTenant);
    });

    it('should have the property scaleUnitId (base name: "scaleUnitId")', function() {
      // uncomment below and update the code to test the property scaleUnitId
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property devAccountId (base name: "devAccountId")', function() {
      // uncomment below and update the code to test the property devAccountId
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property isDevTenant (base name: "isDevTenant")', function() {
      // uncomment below and update the code to test the property isDevTenant
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property sites (base name: "sites")', function() {
      // uncomment below and update the code to test the property sites
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property masterCatalogs (base name: "masterCatalogs")', function() {
      // uncomment below and update the code to test the property masterCatalogs
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property domain (base name: "domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property routingTargetInfo (base name: "routingTargetInfo")', function() {
      // uncomment below and update the code to test the property routingTargetInfo
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property supportsCustomExtensions (base name: "supportsCustomExtensions")', function() {
      // uncomment below and update the code to test the property supportsCustomExtensions
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property mozuInstanceId (base name: "mozuInstanceId")', function() {
      // uncomment below and update the code to test the property mozuInstanceId
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property attributes (base name: "attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property omsMerchantId (base name: "omsMerchantId")', function() {
      // uncomment below and update the code to test the property omsMerchantId
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property createDate (base name: "createDate")', function() {
      // uncomment below and update the code to test the property createDate
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property isDeleted (base name: "isDeleted")', function() {
      // uncomment below and update the code to test the property isDeleted
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property deleteDate (base name: "deleteDate")', function() {
      // uncomment below and update the code to test the property deleteDate
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property updateDate (base name: "updateDate")', function() {
      // uncomment below and update the code to test the property updateDate
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new KiboAppDevService.MozuTenantContractsTenant();
      //expect(instance).to.be();
    });

  });

}));
