/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuAppDevContractsDeveloperAccountAppType', function() {
    it('should create an instance of MozuAppDevContractsDeveloperAccountAppType', function() {
      // uncomment below and update the code to test MozuAppDevContractsDeveloperAccountAppType
      //var instane = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
      //expect(instance).to.be.a(KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType);
    });

    it('should have the property developerAccountAppTypeId (base name: "developerAccountAppTypeId")', function() {
      // uncomment below and update the code to test the property developerAccountAppTypeId
      //var instane = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
      //expect(instance).to.be();
    });

    it('should have the property developerAccountTypeId (base name: "developerAccountTypeId")', function() {
      // uncomment below and update the code to test the property developerAccountTypeId
      //var instane = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
      //expect(instance).to.be();
    });

    it('should have the property applicationTypeId (base name: "applicationTypeId")', function() {
      // uncomment below and update the code to test the property applicationTypeId
      //var instane = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
      //expect(instance).to.be();
    });

    it('should have the property devAccountTypeEnabled (base name: "devAccountTypeEnabled")', function() {
      // uncomment below and update the code to test the property devAccountTypeEnabled
      //var instane = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
      //expect(instance).to.be();
    });

    it('should have the property applicationTypeName (base name: "applicationTypeName")', function() {
      // uncomment below and update the code to test the property applicationTypeName
      //var instane = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
      //expect(instance).to.be();
    });

    it('should have the property developerAccountTypeName (base name: "developerAccountTypeName")', function() {
      // uncomment below and update the code to test the property developerAccountTypeName
      //var instane = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
      //expect(instance).to.be();
    });

    it('should have the property developerAccountAppTypeEnabled (base name: "developerAccountAppTypeEnabled")', function() {
      // uncomment below and update the code to test the property developerAccountAppTypeEnabled
      //var instane = new KiboAppDevService.MozuAppDevContractsDeveloperAccountAppType();
      //expect(instance).to.be();
    });

  });

}));
