/**
 * Kibo AppDev Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KiboAppDevService);
  }
}(this, function(expect, KiboAppDevService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KiboAppDevService.MozuCoreApiContractsUserRole();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MozuCoreApiContractsUserRole', function() {
    it('should create an instance of MozuCoreApiContractsUserRole', function() {
      // uncomment below and update the code to test MozuCoreApiContractsUserRole
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserRole();
      //expect(instance).to.be.a(KiboAppDevService.MozuCoreApiContractsUserRole);
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserRole();
      //expect(instance).to.be();
    });

    it('should have the property assignedInScope (base name: "assignedInScope")', function() {
      // uncomment below and update the code to test the property assignedInScope
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserRole();
      //expect(instance).to.be();
    });

    it('should have the property roleId (base name: "roleId")', function() {
      // uncomment below and update the code to test the property roleId
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserRole();
      //expect(instance).to.be();
    });

    it('should have the property roleName (base name: "roleName")', function() {
      // uncomment below and update the code to test the property roleName
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserRole();
      //expect(instance).to.be();
    });

    it('should have the property auditInfo (base name: "auditInfo")', function() {
      // uncomment below and update the code to test the property auditInfo
      //var instane = new KiboAppDevService.MozuCoreApiContractsUserRole();
      //expect(instance).to.be();
    });

  });

}));
